//
// AppModulesShopsSchemasInviteStaffRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AppModulesShopsSchemasInviteStaffRequest: Sendable, Codable, Hashable {

    public var userId: Int
    public var role: StaffRole

    public init(userId: Int, role: StaffRole) {
        self.userId = userId
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(role, forKey: .role)
    }
}

