//
// AssignRoleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssignRoleRequest: Sendable, Codable, Hashable {

    public var roleId: Int

    public init(roleId: Int) {
        self.roleId = roleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roleId = "role_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(roleId, forKey: .roleId)
    }
}

