//
// AttributeDataType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AttributeDataType: String, Sendable, Codable, CaseIterable {
    case text = "text"
    case number = "number"
    case boolean = "boolean"
    case select = "select"
    case multiSelect = "multi_select"
}
