//
// AuditLogRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuditLogRead: Sendable, Codable, Hashable {

    public var id: Int
    public var actorId: Int
    public var action: String
    public var targetType: String
    public var targetId: Int
    public var before: [String: JSONValue]?
    public var after: [String: JSONValue]?
    public var reason: String?
    public var createdAt: Date

    public init(id: Int, actorId: Int, action: String, targetType: String, targetId: Int, before: [String: JSONValue]?, after: [String: JSONValue]?, reason: String?, createdAt: Date) {
        self.id = id
        self.actorId = actorId
        self.action = action
        self.targetType = targetType
        self.targetId = targetId
        self.before = before
        self.after = after
        self.reason = reason
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case actorId = "actor_id"
        case action
        case targetType = "target_type"
        case targetId = "target_id"
        case before
        case after
        case reason
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(actorId, forKey: .actorId)
        try container.encode(action, forKey: .action)
        try container.encode(targetType, forKey: .targetType)
        try container.encode(targetId, forKey: .targetId)
        try container.encode(before, forKey: .before)
        try container.encode(after, forKey: .after)
        try container.encode(reason, forKey: .reason)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension AuditLogRead: Identifiable {}
