//
// BankAccountCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BankAccountCreateRequest: Sendable, Codable, Hashable {

    public var ownerType: BankOwnerType
    public var shopId: Int?
    public var accountHolderName: String
    public var bankName: String
    public var accountNumber: String
    public var isPrimary: Bool? = false

    public init(ownerType: BankOwnerType, shopId: Int? = nil, accountHolderName: String, bankName: String, accountNumber: String, isPrimary: Bool? = false) {
        self.ownerType = ownerType
        self.shopId = shopId
        self.accountHolderName = accountHolderName
        self.bankName = bankName
        self.accountNumber = accountNumber
        self.isPrimary = isPrimary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ownerType = "owner_type"
        case shopId = "shop_id"
        case accountHolderName = "account_holder_name"
        case bankName = "bank_name"
        case accountNumber = "account_number"
        case isPrimary = "is_primary"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ownerType, forKey: .ownerType)
        try container.encodeIfPresent(shopId, forKey: .shopId)
        try container.encode(accountHolderName, forKey: .accountHolderName)
        try container.encode(bankName, forKey: .bankName)
        try container.encode(accountNumber, forKey: .accountNumber)
        try container.encodeIfPresent(isPrimary, forKey: .isPrimary)
    }
}

