//
// BankAccountRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BankAccountRead: Sendable, Codable, Hashable {

    public var id: Int
    public var sellerId: Int?
    public var shopId: Int?
    public var ownerType: BankOwnerType
    public var accountHolderName: String
    public var bankName: String
    public var isPrimary: Bool
    public var verified: Bool
    public var createdAt: Date

    public init(id: Int, sellerId: Int?, shopId: Int?, ownerType: BankOwnerType, accountHolderName: String, bankName: String, isPrimary: Bool, verified: Bool, createdAt: Date) {
        self.id = id
        self.sellerId = sellerId
        self.shopId = shopId
        self.ownerType = ownerType
        self.accountHolderName = accountHolderName
        self.bankName = bankName
        self.isPrimary = isPrimary
        self.verified = verified
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case sellerId = "seller_id"
        case shopId = "shop_id"
        case ownerType = "owner_type"
        case accountHolderName = "account_holder_name"
        case bankName = "bank_name"
        case isPrimary = "is_primary"
        case verified
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(sellerId, forKey: .sellerId)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(ownerType, forKey: .ownerType)
        try container.encode(accountHolderName, forKey: .accountHolderName)
        try container.encode(bankName, forKey: .bankName)
        try container.encode(isPrimary, forKey: .isPrimary)
        try container.encode(verified, forKey: .verified)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension BankAccountRead: Identifiable {}
