//
// BankOwnerType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BankOwnerType: String, Sendable, Codable, CaseIterable {
    case seller = "seller"
    case shop = "shop"
}
