//
// BrandPublicRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrandPublicRead: Sendable, Codable, Hashable {

    public var id: Int
    public var name: String
    public var logoUrl: String?
    public var isVerified: Bool

    public init(id: Int, name: String, logoUrl: String?, isVerified: Bool) {
        self.id = id
        self.name = name
        self.logoUrl = logoUrl
        self.isVerified = isVerified
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case logoUrl = "logo_url"
        case isVerified = "is_verified"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(logoUrl, forKey: .logoUrl)
        try container.encode(isVerified, forKey: .isVerified)
    }
}


extension BrandPublicRead: Identifiable {}
