//
// BrandFacetRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrandFacetRead: Sendable, Codable, Hashable {

    public var id: Int
    public var name: String
    public var count: Int

    public init(id: Int, name: String, count: Int) {
        self.id = id
        self.name = name
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(count, forKey: .count)
    }
}


extension BrandFacetRead: Identifiable {}
