//
// BrandRequestCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrandRequestCreate: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public var shopId: Int
    public var name: String
    public var logoUrl: String?

    public init(shopId: Int, name: String, logoUrl: String? = nil) {
        self.shopId = shopId
        self.name = name
        self.logoUrl = logoUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shopId = "shop_id"
        case name
        case logoUrl = "logo_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
    }
}

