//
// CartVariantRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CartVariantRead: Sendable, Codable, Hashable {

    public var id: Int
    public var attributes: [String: AttributesValue]

    public init(id: Int, attributes: [String: AttributesValue]) {
        self.id = id
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(attributes, forKey: .attributes)
    }
}


extension CartVariantRead: Identifiable {}
