//
// CartItemUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CartItemUpdateRequest: Sendable, Codable, Hashable {

    public static let quantityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var quantity: Int

    public init(quantity: Int) {
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(quantity, forKey: .quantity)
    }
}

