//
// CashCollectionRecordItemRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CashCollectionRecordItemRead: Sendable, Codable, Hashable {

    public static let amountRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var id: Int
    public var cashCollectionRecordId: Int
    public var pickupPointHoldingItemId: Int
    public var quantityCollected: Int
    public var amount: String

    public init(id: Int, cashCollectionRecordId: Int, pickupPointHoldingItemId: Int, quantityCollected: Int, amount: String) {
        self.id = id
        self.cashCollectionRecordId = cashCollectionRecordId
        self.pickupPointHoldingItemId = pickupPointHoldingItemId
        self.quantityCollected = quantityCollected
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case cashCollectionRecordId = "cash_collection_record_id"
        case pickupPointHoldingItemId = "pickup_point_holding_item_id"
        case quantityCollected = "quantity_collected"
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(cashCollectionRecordId, forKey: .cashCollectionRecordId)
        try container.encode(pickupPointHoldingItemId, forKey: .pickupPointHoldingItemId)
        try container.encode(quantityCollected, forKey: .quantityCollected)
        try container.encode(amount, forKey: .amount)
    }
}


extension CashCollectionRecordItemRead: Identifiable {}
