//
// CashCollectionRecordRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CashCollectionRecordRead: Sendable, Codable, Hashable {

    public static let amountCollectedRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var id: Int
    public var orderShopGroupId: Int
    public var amountCollected: String
    public var collectedByStaffId: Int
    public var collectedAt: Date
    public var items: [CashCollectionRecordItemRead]?

    public init(id: Int, orderShopGroupId: Int, amountCollected: String, collectedByStaffId: Int, collectedAt: Date, items: [CashCollectionRecordItemRead]? = nil) {
        self.id = id
        self.orderShopGroupId = orderShopGroupId
        self.amountCollected = amountCollected
        self.collectedByStaffId = collectedByStaffId
        self.collectedAt = collectedAt
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case orderShopGroupId = "order_shop_group_id"
        case amountCollected = "amount_collected"
        case collectedByStaffId = "collected_by_staff_id"
        case collectedAt = "collected_at"
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(orderShopGroupId, forKey: .orderShopGroupId)
        try container.encode(amountCollected, forKey: .amountCollected)
        try container.encode(collectedByStaffId, forKey: .collectedByStaffId)
        try container.encode(collectedAt, forKey: .collectedAt)
        try container.encodeIfPresent(items, forKey: .items)
    }
}


extension CashCollectionRecordRead: Identifiable {}
