//
// CatalogSort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CatalogSort: String, Sendable, Codable, CaseIterable {
    case relevance = "relevance"
    case newest = "newest"
    case priceAsc = "price_asc"
    case priceDesc = "price_desc"
}
