//
// CatalogFacetsRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CatalogFacetsRead: Sendable, Codable, Hashable {

    public var brands: [BrandFacetRead]
    public var price: PriceRangeRead

    public init(brands: [BrandFacetRead], price: PriceRangeRead) {
        self.brands = brands
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brands
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brands, forKey: .brands)
        try container.encode(price, forKey: .price)
    }
}

