//
// CategoryRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CategoryRead: Sendable, Codable, Hashable {

    public var id: Int
    public var parentId: Int?
    public var slug: String
    public var iconUrl: String?
    public var sortOrder: Int
    public var isLeaf: Bool
    public var isActive: Bool
    public var requiresDocuments: Bool
    public var requiredDocumentTypes: [String]?
    public var allowsVariants: Bool
    public var returnWindowDays: Int?
    public var defaultCommissionRuleId: Int?
    public var createdAt: Date
    public var updatedAt: Date
    public var translations: [TranslationRead]?

    public init(id: Int, parentId: Int?, slug: String, iconUrl: String?, sortOrder: Int, isLeaf: Bool, isActive: Bool, requiresDocuments: Bool, requiredDocumentTypes: [String]?, allowsVariants: Bool, returnWindowDays: Int?, defaultCommissionRuleId: Int?, createdAt: Date, updatedAt: Date, translations: [TranslationRead]? = nil) {
        self.id = id
        self.parentId = parentId
        self.slug = slug
        self.iconUrl = iconUrl
        self.sortOrder = sortOrder
        self.isLeaf = isLeaf
        self.isActive = isActive
        self.requiresDocuments = requiresDocuments
        self.requiredDocumentTypes = requiredDocumentTypes
        self.allowsVariants = allowsVariants
        self.returnWindowDays = returnWindowDays
        self.defaultCommissionRuleId = defaultCommissionRuleId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.translations = translations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case parentId = "parent_id"
        case slug
        case iconUrl = "icon_url"
        case sortOrder = "sort_order"
        case isLeaf = "is_leaf"
        case isActive = "is_active"
        case requiresDocuments = "requires_documents"
        case requiredDocumentTypes = "required_document_types"
        case allowsVariants = "allows_variants"
        case returnWindowDays = "return_window_days"
        case defaultCommissionRuleId = "default_commission_rule_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case translations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(parentId, forKey: .parentId)
        try container.encode(slug, forKey: .slug)
        try container.encode(iconUrl, forKey: .iconUrl)
        try container.encode(sortOrder, forKey: .sortOrder)
        try container.encode(isLeaf, forKey: .isLeaf)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(requiresDocuments, forKey: .requiresDocuments)
        try container.encode(requiredDocumentTypes, forKey: .requiredDocumentTypes)
        try container.encode(allowsVariants, forKey: .allowsVariants)
        try container.encode(returnWindowDays, forKey: .returnWindowDays)
        try container.encode(defaultCommissionRuleId, forKey: .defaultCommissionRuleId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(translations, forKey: .translations)
    }
}


extension CategoryRead: Identifiable {}
