//
// CategoryUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PATCH semantics. parent_id is changed via /move only. is_active&#x3D;False goes through the deactivate preview/confirm flow — reactivation (True) is allowed here since it never destroys data. */
public struct CategoryUpdate: Sendable, Codable, Hashable {

    public static let returnWindowDaysRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var slug: String?
    public var iconUrl: String?
    public var sortOrder: Int?
    public var isActive: Bool?
    public var requiresDocuments: Bool?
    public var requiredDocumentTypes: [String]?
    public var allowsVariants: Bool?
    public var returnWindowDays: Int?
    public var defaultCommissionRuleId: Int?
    public var translations: [TranslationIn]?

    public init(slug: String? = nil, iconUrl: String? = nil, sortOrder: Int? = nil, isActive: Bool? = nil, requiresDocuments: Bool? = nil, requiredDocumentTypes: [String]? = nil, allowsVariants: Bool? = nil, returnWindowDays: Int? = nil, defaultCommissionRuleId: Int? = nil, translations: [TranslationIn]? = nil) {
        self.slug = slug
        self.iconUrl = iconUrl
        self.sortOrder = sortOrder
        self.isActive = isActive
        self.requiresDocuments = requiresDocuments
        self.requiredDocumentTypes = requiredDocumentTypes
        self.allowsVariants = allowsVariants
        self.returnWindowDays = returnWindowDays
        self.defaultCommissionRuleId = defaultCommissionRuleId
        self.translations = translations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slug
        case iconUrl = "icon_url"
        case sortOrder = "sort_order"
        case isActive = "is_active"
        case requiresDocuments = "requires_documents"
        case requiredDocumentTypes = "required_document_types"
        case allowsVariants = "allows_variants"
        case returnWindowDays = "return_window_days"
        case defaultCommissionRuleId = "default_commission_rule_id"
        case translations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(iconUrl, forKey: .iconUrl)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(requiresDocuments, forKey: .requiresDocuments)
        try container.encodeIfPresent(requiredDocumentTypes, forKey: .requiredDocumentTypes)
        try container.encodeIfPresent(allowsVariants, forKey: .allowsVariants)
        try container.encodeIfPresent(returnWindowDays, forKey: .returnWindowDays)
        try container.encodeIfPresent(defaultCommissionRuleId, forKey: .defaultCommissionRuleId)
        try container.encodeIfPresent(translations, forKey: .translations)
    }
}

