//
// CategoryAssignmentRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CategoryAssignmentRead: Sendable, Codable, Hashable {

    public var id: Int
    public var shopId: Int
    public var categoryId: Int
    public var status: CategoryAssignmentStatus
    public var documentIds: [Int]?
    public var rejectionReason: String?
    public var needsReverification: Bool
    public var createdAt: Date

    public init(id: Int, shopId: Int, categoryId: Int, status: CategoryAssignmentStatus, documentIds: [Int]?, rejectionReason: String?, needsReverification: Bool, createdAt: Date) {
        self.id = id
        self.shopId = shopId
        self.categoryId = categoryId
        self.status = status
        self.documentIds = documentIds
        self.rejectionReason = rejectionReason
        self.needsReverification = needsReverification
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case shopId = "shop_id"
        case categoryId = "category_id"
        case status
        case documentIds = "document_ids"
        case rejectionReason = "rejection_reason"
        case needsReverification = "needs_reverification"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(status, forKey: .status)
        try container.encode(documentIds, forKey: .documentIds)
        try container.encode(rejectionReason, forKey: .rejectionReason)
        try container.encode(needsReverification, forKey: .needsReverification)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension CategoryAssignmentRead: Identifiable {}
