//
// CategoryAttributeIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CategoryAttributeIn: Sendable, Codable, Hashable {

    public static let translationsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var key: String
    public var dataType: AttributeDataType
    public var options: [String]?
    public var unit: String?
    public var isRequired: Bool? = false
    public var isFilterable: Bool? = false
    public var isInherited: Bool? = false
    public var isVariantDefining: Bool? = false
    public var sortOrder: Int? = 0
    public var translations: [AttributeTranslationIn]

    public init(key: String, dataType: AttributeDataType, options: [String]? = nil, unit: String? = nil, isRequired: Bool? = false, isFilterable: Bool? = false, isInherited: Bool? = false, isVariantDefining: Bool? = false, sortOrder: Int? = 0, translations: [AttributeTranslationIn]) {
        self.key = key
        self.dataType = dataType
        self.options = options
        self.unit = unit
        self.isRequired = isRequired
        self.isFilterable = isFilterable
        self.isInherited = isInherited
        self.isVariantDefining = isVariantDefining
        self.sortOrder = sortOrder
        self.translations = translations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case dataType = "data_type"
        case options
        case unit
        case isRequired = "is_required"
        case isFilterable = "is_filterable"
        case isInherited = "is_inherited"
        case isVariantDefining = "is_variant_defining"
        case sortOrder = "sort_order"
        case translations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(dataType, forKey: .dataType)
        try container.encodeIfPresent(options, forKey: .options)
        try container.encodeIfPresent(unit, forKey: .unit)
        try container.encodeIfPresent(isRequired, forKey: .isRequired)
        try container.encodeIfPresent(isFilterable, forKey: .isFilterable)
        try container.encodeIfPresent(isInherited, forKey: .isInherited)
        try container.encodeIfPresent(isVariantDefining, forKey: .isVariantDefining)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encode(translations, forKey: .translations)
    }
}

