//
// CategoryCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CategoryCreate: Sendable, Codable, Hashable {

    public static let returnWindowDaysRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let translationsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var parentId: Int?
    public var slug: String
    public var iconUrl: String?
    public var sortOrder: Int? = 0
    public var requiresDocuments: Bool? = false
    public var requiredDocumentTypes: [String]?
    public var allowsVariants: Bool? = true
    public var returnWindowDays: Int?
    public var translations: [TranslationIn]

    public init(parentId: Int? = nil, slug: String, iconUrl: String? = nil, sortOrder: Int? = 0, requiresDocuments: Bool? = false, requiredDocumentTypes: [String]? = nil, allowsVariants: Bool? = true, returnWindowDays: Int? = nil, translations: [TranslationIn]) {
        self.parentId = parentId
        self.slug = slug
        self.iconUrl = iconUrl
        self.sortOrder = sortOrder
        self.requiresDocuments = requiresDocuments
        self.requiredDocumentTypes = requiredDocumentTypes
        self.allowsVariants = allowsVariants
        self.returnWindowDays = returnWindowDays
        self.translations = translations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parentId = "parent_id"
        case slug
        case iconUrl = "icon_url"
        case sortOrder = "sort_order"
        case requiresDocuments = "requires_documents"
        case requiredDocumentTypes = "required_document_types"
        case allowsVariants = "allows_variants"
        case returnWindowDays = "return_window_days"
        case translations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(iconUrl, forKey: .iconUrl)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(requiresDocuments, forKey: .requiresDocuments)
        try container.encodeIfPresent(requiredDocumentTypes, forKey: .requiredDocumentTypes)
        try container.encodeIfPresent(allowsVariants, forKey: .allowsVariants)
        try container.encodeIfPresent(returnWindowDays, forKey: .returnWindowDays)
        try container.encode(translations, forKey: .translations)
    }
}

