//
// CheckoutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CheckoutRequest: Sendable, Codable, Hashable {

    public var shippingAddress: ShippingAddressIn
    public var paymentMethod: PaymentMethod

    public init(shippingAddress: ShippingAddressIn, paymentMethod: PaymentMethod) {
        self.shippingAddress = shippingAddress
        self.paymentMethod = paymentMethod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shippingAddress = "shipping_address"
        case paymentMethod = "payment_method"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shippingAddress, forKey: .shippingAddress)
        try container.encode(paymentMethod, forKey: .paymentMethod)
    }
}

