//
// CheckoutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CheckoutRequest: Sendable, Codable, Hashable {

    public var recipient: Recipient
    public var pickupPointId: Int
    public var paymentMethod: PaymentMethod

    public init(recipient: Recipient, pickupPointId: Int, paymentMethod: PaymentMethod) {
        self.recipient = recipient
        self.pickupPointId = pickupPointId
        self.paymentMethod = paymentMethod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipient
        case pickupPointId = "pickup_point_id"
        case paymentMethod = "payment_method"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipient, forKey: .recipient)
        try container.encode(pickupPointId, forKey: .pickupPointId)
        try container.encode(paymentMethod, forKey: .paymentMethod)
    }
}

