//
// CollectItemInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CollectItemInput: Sendable, Codable, Hashable {

    public static let quantityCollectedRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var holdingItemId: Int
    public var quantityCollected: Int

    public init(holdingItemId: Int, quantityCollected: Int) {
        self.holdingItemId = holdingItemId
        self.quantityCollected = quantityCollected
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case holdingItemId = "holding_item_id"
        case quantityCollected = "quantity_collected"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(holdingItemId, forKey: .holdingItemId)
        try container.encode(quantityCollected, forKey: .quantityCollected)
    }
}

