//
// CommissionResolutionRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommissionResolutionRead: Sendable, Codable, Hashable {

    public static let amountRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public static let percentRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public static let flatFeeAmountRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var ruleId: Int
    public var amount: String?
    public var calculationType: CommissionCalculationType
    public var percent: String?
    public var flatFeeAmount: String?
    public var currency: String

    public init(ruleId: Int, amount: String? = nil, calculationType: CommissionCalculationType, percent: String?, flatFeeAmount: String?, currency: String) {
        self.ruleId = ruleId
        self.amount = amount
        self.calculationType = calculationType
        self.percent = percent
        self.flatFeeAmount = flatFeeAmount
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ruleId = "rule_id"
        case amount
        case calculationType = "calculation_type"
        case percent
        case flatFeeAmount = "flat_fee_amount"
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ruleId, forKey: .ruleId)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encode(calculationType, forKey: .calculationType)
        try container.encode(percent, forKey: .percent)
        try container.encode(flatFeeAmount, forKey: .flatFeeAmount)
        try container.encode(currency, forKey: .currency)
    }
}

