//
// CommissionRuleRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommissionRuleRead: Sendable, Codable, Hashable {

    public static let percentRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public static let flatFeeAmountRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var id: Int
    public var scopeType: CommissionScopeType
    public var scopeId: Int?
    public var categoryId: Int?
    public var calculationType: CommissionCalculationType
    public var percent: String?
    public var flatFeeAmount: String?
    public var currency: String
    public var tiers: [[String: JSONValue]]?
    public var isActive: Bool
    public var effectiveFrom: Date
    public var effectiveTo: Date?
    public var createdBy: Int
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: Int, scopeType: CommissionScopeType, scopeId: Int?, categoryId: Int?, calculationType: CommissionCalculationType, percent: String?, flatFeeAmount: String?, currency: String, tiers: [[String: JSONValue]]?, isActive: Bool, effectiveFrom: Date, effectiveTo: Date?, createdBy: Int, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.scopeType = scopeType
        self.scopeId = scopeId
        self.categoryId = categoryId
        self.calculationType = calculationType
        self.percent = percent
        self.flatFeeAmount = flatFeeAmount
        self.currency = currency
        self.tiers = tiers
        self.isActive = isActive
        self.effectiveFrom = effectiveFrom
        self.effectiveTo = effectiveTo
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case scopeType = "scope_type"
        case scopeId = "scope_id"
        case categoryId = "category_id"
        case calculationType = "calculation_type"
        case percent
        case flatFeeAmount = "flat_fee_amount"
        case currency
        case tiers
        case isActive = "is_active"
        case effectiveFrom = "effective_from"
        case effectiveTo = "effective_to"
        case createdBy = "created_by"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(scopeType, forKey: .scopeType)
        try container.encode(scopeId, forKey: .scopeId)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(calculationType, forKey: .calculationType)
        try container.encode(percent, forKey: .percent)
        try container.encode(flatFeeAmount, forKey: .flatFeeAmount)
        try container.encode(currency, forKey: .currency)
        try container.encode(tiers, forKey: .tiers)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(effectiveFrom, forKey: .effectiveFrom)
        try container.encode(effectiveTo, forKey: .effectiveTo)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension CommissionRuleRead: Identifiable {}
