//
// ConfirmCollectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConfirmCollectionRequest: Sendable, Codable, Hashable {

    public static let itemsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var items: [CollectItemInput]
    public var amountCollected: AmountCollected

    public init(items: [CollectItemInput], amountCollected: AmountCollected) {
        self.items = items
        self.amountCollected = amountCollected
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case amountCollected = "amount_collected"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(amountCollected, forKey: .amountCollected)
    }
}

