//
// DeclareReconciliationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeclareReconciliationRequest: Sendable, Codable, Hashable {

    public var declaredAmount: DeclaredAmount

    public init(declaredAmount: DeclaredAmount) {
        self.declaredAmount = declaredAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case declaredAmount = "declared_amount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(declaredAmount, forKey: .declaredAmount)
    }
}

