//
// DocumentSubmitRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DocumentSubmitRequest: Sendable, Codable, Hashable {

    public var type: DocumentType
    public var fileUrl: String
    public var shopId: Int?

    public init(type: DocumentType, fileUrl: String, shopId: Int? = nil) {
        self.type = type
        self.fileUrl = fileUrl
        self.shopId = shopId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case fileUrl = "file_url"
        case shopId = "shop_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(fileUrl, forKey: .fileUrl)
        try container.encodeIfPresent(shopId, forKey: .shopId)
    }
}

