//
// DocumentReviewRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DocumentReviewRequest: Sendable, Codable, Hashable {

    public var status: DocumentStatus
    public var rejectionReason: String?

    public init(status: DocumentStatus, rejectionReason: String? = nil) {
        self.status = status
        self.rejectionReason = rejectionReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case rejectionReason = "rejection_reason"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(rejectionReason, forKey: .rejectionReason)
    }
}

