//
// LedgerStatementRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LedgerStatementRead: Sendable, Codable, Hashable {

    public static let balanceRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var shopId: Int
    public var periodStart: Date
    public var periodEnd: Date
    public var balance: String
    public var entries: [LedgerEntryRead]

    public init(shopId: Int, periodStart: Date, periodEnd: Date, balance: String, entries: [LedgerEntryRead]) {
        self.shopId = shopId
        self.periodStart = periodStart
        self.periodEnd = periodEnd
        self.balance = balance
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shopId = "shop_id"
        case periodStart = "period_start"
        case periodEnd = "period_end"
        case balance
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(periodStart, forKey: .periodStart)
        try container.encode(periodEnd, forKey: .periodEnd)
        try container.encode(balance, forKey: .balance)
        try container.encode(entries, forKey: .entries)
    }
}

