//
// ManualAdjustmentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ManualAdjustmentRequest: Sendable, Codable, Hashable {

    public static let noteRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var amount: Amount
    public var note: String

    public init(amount: Amount, note: String) {
        self.amount = amount
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(note, forKey: .note)
    }
}

