//
// ModerationConfigRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationConfigRead: Sendable, Codable, Hashable {

    public var sensitiveFields: [String]
    public var updatedAt: Date
    public var updatedBy: Int?

    public init(sensitiveFields: [String], updatedAt: Date, updatedBy: Int?) {
        self.sensitiveFields = sensitiveFields
        self.updatedAt = updatedAt
        self.updatedBy = updatedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sensitiveFields = "sensitive_fields"
        case updatedAt = "updated_at"
        case updatedBy = "updated_by"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sensitiveFields, forKey: .sensitiveFields)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(updatedBy, forKey: .updatedBy)
    }
}

