//
// ModerationConfigUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModerationConfigUpdate: Sendable, Codable, Hashable {

    public static let sensitiveFieldsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var sensitiveFields: [String]

    public init(sensitiveFields: [String]) {
        self.sensitiveFields = sensitiveFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sensitiveFields = "sensitive_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sensitiveFields, forKey: .sensitiveFields)
    }
}

