//
// OrderLineStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Owned by RefundService (Doc 04 §3.1a). */
public enum OrderLineStatus: String, Sendable, Codable, CaseIterable {
    case active = "active"
    case returnPending = "return_pending"
    case returnedToPoint = "returned_to_point"
    case refunded = "refunded"
}
