//
// OrderShopGroupStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OrderShopGroupStatus: String, Sendable, Codable, CaseIterable {
    case pending = "pending"
    case confirmed = "confirmed"
    case preparing = "preparing"
    case shipped = "shipped"
    case delivered = "delivered"
    case cancelled = "cancelled"
    case returnRequested = "return_requested"
    case returned = "returned"
    case refunded = "refunded"
    case arrivedAtPoint = "arrived_at_point"
    case partiallyCollected = "partially_collected"
    case rejectedByBuyer = "rejected_by_buyer"
    case returnToSeller = "return_to_seller"
}
