//
// OrderLineDetailRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Seller/admin only — includes the frozen commission (§2.5). */
public struct OrderLineDetailRead: Sendable, Codable, Hashable {

    public static let unitPriceRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public static let lineTotalRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public static let commissionAmountRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var id: Int
    public var productId: Int
    public var variantId: Int?
    public var productTitleSnapshot: String
    public var skuSnapshot: String
    public var unitPrice: String
    public var quantity: Int
    public var lineTotal: String
    public var status: OrderLineStatus
    public var createdAt: Date
    public var commissionRuleId: Int?
    public var commissionAmount: String?

    public init(id: Int, productId: Int, variantId: Int?, productTitleSnapshot: String, skuSnapshot: String, unitPrice: String, quantity: Int, lineTotal: String, status: OrderLineStatus, createdAt: Date, commissionRuleId: Int?, commissionAmount: String?) {
        self.id = id
        self.productId = productId
        self.variantId = variantId
        self.productTitleSnapshot = productTitleSnapshot
        self.skuSnapshot = skuSnapshot
        self.unitPrice = unitPrice
        self.quantity = quantity
        self.lineTotal = lineTotal
        self.status = status
        self.createdAt = createdAt
        self.commissionRuleId = commissionRuleId
        self.commissionAmount = commissionAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case productId = "product_id"
        case variantId = "variant_id"
        case productTitleSnapshot = "product_title_snapshot"
        case skuSnapshot = "sku_snapshot"
        case unitPrice = "unit_price"
        case quantity
        case lineTotal = "line_total"
        case status
        case createdAt = "created_at"
        case commissionRuleId = "commission_rule_id"
        case commissionAmount = "commission_amount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(productId, forKey: .productId)
        try container.encode(variantId, forKey: .variantId)
        try container.encode(productTitleSnapshot, forKey: .productTitleSnapshot)
        try container.encode(skuSnapshot, forKey: .skuSnapshot)
        try container.encode(unitPrice, forKey: .unitPrice)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(lineTotal, forKey: .lineTotal)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(commissionRuleId, forKey: .commissionRuleId)
        try container.encode(commissionAmount, forKey: .commissionAmount)
    }
}


extension OrderLineDetailRead: Identifiable {}
