//
// OrderLineStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OrderLineStatus: String, Sendable, Codable, CaseIterable {
    case active = "active"
    case returned = "returned"
    case refunded = "refunded"
}
