//
// OrderShopGroupRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Buyer-safe — no commission_total/payout_amount. */
public struct OrderShopGroupRead: Sendable, Codable, Hashable {

    public static let subtotalRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public static let shippingFeeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var id: Int
    public var orderId: Int
    public var shopId: Int
    public var status: OrderShopGroupStatus
    public var subtotal: String
    public var shippingFee: String
    public var cancellationReason: String?
    public var warehouseReceivedAt: Date?
    public var deliveredAt: Date?
    public var createdAt: Date
    public var updatedAt: Date
    public var shop: ShopSummaryRead
    public var lines: [OrderLineRead]?

    public init(id: Int, orderId: Int, shopId: Int, status: OrderShopGroupStatus, subtotal: String, shippingFee: String, cancellationReason: String?, warehouseReceivedAt: Date?, deliveredAt: Date?, createdAt: Date, updatedAt: Date, shop: ShopSummaryRead, lines: [OrderLineRead]? = nil) {
        self.id = id
        self.orderId = orderId
        self.shopId = shopId
        self.status = status
        self.subtotal = subtotal
        self.shippingFee = shippingFee
        self.cancellationReason = cancellationReason
        self.warehouseReceivedAt = warehouseReceivedAt
        self.deliveredAt = deliveredAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.shop = shop
        self.lines = lines
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case orderId = "order_id"
        case shopId = "shop_id"
        case status
        case subtotal
        case shippingFee = "shipping_fee"
        case cancellationReason = "cancellation_reason"
        case warehouseReceivedAt = "warehouse_received_at"
        case deliveredAt = "delivered_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case shop
        case lines
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(orderId, forKey: .orderId)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(status, forKey: .status)
        try container.encode(subtotal, forKey: .subtotal)
        try container.encode(shippingFee, forKey: .shippingFee)
        try container.encode(cancellationReason, forKey: .cancellationReason)
        try container.encode(warehouseReceivedAt, forKey: .warehouseReceivedAt)
        try container.encode(deliveredAt, forKey: .deliveredAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(shop, forKey: .shop)
        try container.encodeIfPresent(lines, forKey: .lines)
    }
}


extension OrderShopGroupRead: Identifiable {}
