//
// PasswordResetConfirm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PasswordResetConfirm: Sendable, Codable, Hashable {

    public static let codeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^\\d{6}$/")
    public static let newPasswordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public var email: String
    public var code: String
    public var newPassword: String

    public init(email: String, code: String, newPassword: String) {
        self.email = email
        self.code = code
        self.newPassword = newPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case code
        case newPassword = "new_password"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(code, forKey: .code)
        try container.encode(newPassword, forKey: .newPassword)
    }
}

