//
// PickupPointShipmentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PickupPointShipmentStatus: String, Sendable, Codable, CaseIterable {
    case dispatched = "dispatched"
    case inTransit = "in_transit"
    case arrived = "arrived"
    case discrepancy = "discrepancy"
}
