//
// PickupPointStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PickupPointStatus: String, Sendable, Codable, CaseIterable {
    case pendingSetup = "pending_setup"
    case active = "active"
    case temporarilyClosed = "temporarily_closed"
    case closed = "closed"
}
