//
// PickupPointUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PickupPointUpdateRequest: Sendable, Codable, Hashable {

    public static let capacityUnitsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var name: String?
    public var address: [String: JSONValue]?
    public var latitude: Latitude1?
    public var longitude: Longitude1?
    public var capacityUnits: Int?
    public var operatingHours: [String: JSONValue]?
    public var contactPhone: String?
    public var regionId: Int?

    public init(name: String? = nil, address: [String: JSONValue]? = nil, latitude: Latitude1? = nil, longitude: Longitude1? = nil, capacityUnits: Int? = nil, operatingHours: [String: JSONValue]? = nil, contactPhone: String? = nil, regionId: Int? = nil) {
        self.name = name
        self.address = address
        self.latitude = latitude
        self.longitude = longitude
        self.capacityUnits = capacityUnits
        self.operatingHours = operatingHours
        self.contactPhone = contactPhone
        self.regionId = regionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case address
        case latitude
        case longitude
        case capacityUnits = "capacity_units"
        case operatingHours = "operating_hours"
        case contactPhone = "contact_phone"
        case regionId = "region_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(capacityUnits, forKey: .capacityUnits)
        try container.encodeIfPresent(operatingHours, forKey: .operatingHours)
        try container.encodeIfPresent(contactPhone, forKey: .contactPhone)
        try container.encodeIfPresent(regionId, forKey: .regionId)
    }
}

