//
// PickupPointCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PickupPointCreateRequest: Sendable, Codable, Hashable {

    public static let capacityUnitsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var name: String
    public var address: [String: JSONValue]
    public var latitude: Latitude
    public var longitude: Longitude
    public var type: PickupPointType?
    public var capacityUnits: Int?
    public var operatingHours: [String: JSONValue]
    public var contactPhone: String
    public var regionId: Int

    public init(name: String, address: [String: JSONValue], latitude: Latitude, longitude: Longitude, type: PickupPointType? = nil, capacityUnits: Int? = nil, operatingHours: [String: JSONValue], contactPhone: String, regionId: Int) {
        self.name = name
        self.address = address
        self.latitude = latitude
        self.longitude = longitude
        self.type = type
        self.capacityUnits = capacityUnits
        self.operatingHours = operatingHours
        self.contactPhone = contactPhone
        self.regionId = regionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case address
        case latitude
        case longitude
        case type
        case capacityUnits = "capacity_units"
        case operatingHours = "operating_hours"
        case contactPhone = "contact_phone"
        case regionId = "region_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(address, forKey: .address)
        try container.encode(latitude, forKey: .latitude)
        try container.encode(longitude, forKey: .longitude)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(capacityUnits, forKey: .capacityUnits)
        try container.encode(operatingHours, forKey: .operatingHours)
        try container.encode(contactPhone, forKey: .contactPhone)
        try container.encode(regionId, forKey: .regionId)
    }
}

