//
// PriceMin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Compared against the card&#39;s price_min */
public struct PriceMin: Sendable, Codable, Hashable {


    public enum CodingKeys: CodingKey, CaseIterable {
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
    }
}

