//
// ProductCardRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductCardRead: Sendable, Codable, Hashable {

    public static let priceMinRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public static let priceMaxRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    public var id: Int
    public var slug: String
    public var title: String
    public var priceMin: String
    public var priceMax: String
    public var inStock: Bool
    public var hasVariants: Bool
    public var imageUrl: String?
    public var shop: ShopSummaryRead
    public var brand: BrandPublicRead?
    public var categoryId: Int
    public var createdAt: Date

    public init(id: Int, slug: String, title: String, priceMin: String, priceMax: String, inStock: Bool, hasVariants: Bool, imageUrl: String?, shop: ShopSummaryRead, brand: BrandPublicRead?, categoryId: Int, createdAt: Date) {
        self.id = id
        self.slug = slug
        self.title = title
        self.priceMin = priceMin
        self.priceMax = priceMax
        self.inStock = inStock
        self.hasVariants = hasVariants
        self.imageUrl = imageUrl
        self.shop = shop
        self.brand = brand
        self.categoryId = categoryId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case slug
        case title
        case priceMin = "price_min"
        case priceMax = "price_max"
        case inStock = "in_stock"
        case hasVariants = "has_variants"
        case imageUrl = "image_url"
        case shop
        case brand
        case categoryId = "category_id"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(slug, forKey: .slug)
        try container.encode(title, forKey: .title)
        try container.encode(priceMin, forKey: .priceMin)
        try container.encode(priceMax, forKey: .priceMax)
        try container.encode(inStock, forKey: .inStock)
        try container.encode(hasVariants, forKey: .hasVariants)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(shop, forKey: .shop)
        try container.encode(brand, forKey: .brand)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension ProductCardRead: Identifiable {}
