//
// ProductImageIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductImageIn: Sendable, Codable, Hashable {

    public var key: String
    public var sortOrder: Int? = 0
    public var isPrimary: Bool? = false

    public init(key: String, sortOrder: Int? = 0, isPrimary: Bool? = false) {
        self.key = key
        self.sortOrder = sortOrder
        self.isPrimary = isPrimary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case sortOrder = "sort_order"
        case isPrimary = "is_primary"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(isPrimary, forKey: .isPrimary)
    }
}

