//
// ProductStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ProductStatus: String, Sendable, Codable, CaseIterable {
    case draft = "draft"
    case pendingReview = "pending_review"
    case approved = "approved"
    case rejected = "rejected"
    case delisted = "delisted"
    case archived = "archived"
}
