//
// ProductVariantUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductVariantUpdate: Sendable, Codable, Hashable {

    public static let stockQuantityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var sku: String?
    public var price: Price1?
    public var stockQuantity: Int?
    public var attributes: [String: AttributesValue]?
    public var imageIds: [Int]?
    public var isActive: Bool?

    public init(sku: String? = nil, price: Price1? = nil, stockQuantity: Int? = nil, attributes: [String: AttributesValue]? = nil, imageIds: [Int]? = nil, isActive: Bool? = nil) {
        self.sku = sku
        self.price = price
        self.stockQuantity = stockQuantity
        self.attributes = attributes
        self.imageIds = imageIds
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sku
        case price
        case stockQuantity = "stock_quantity"
        case attributes
        case imageIds = "image_ids"
        case isActive = "is_active"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sku, forKey: .sku)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(stockQuantity, forKey: .stockQuantity)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(imageIds, forKey: .imageIds)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}

