//
// ProductVariantCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductVariantCreate: Sendable, Codable, Hashable {

    public static let stockQuantityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var sku: String
    public var price: Price
    public var stockQuantity: Int
    public var attributes: [String: AttributesValue]
    public var imageIds: [Int]?

    public init(sku: String, price: Price, stockQuantity: Int, attributes: [String: AttributesValue], imageIds: [Int]? = nil) {
        self.sku = sku
        self.price = price
        self.stockQuantity = stockQuantity
        self.attributes = attributes
        self.imageIds = imageIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sku
        case price
        case stockQuantity = "stock_quantity"
        case attributes
        case imageIds = "image_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sku, forKey: .sku)
        try container.encode(price, forKey: .price)
        try container.encode(stockQuantity, forKey: .stockQuantity)
        try container.encode(attributes, forKey: .attributes)
        try container.encodeIfPresent(imageIds, forKey: .imageIds)
    }
}

