//
// RefundResolveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefundResolveRequest: Sendable, Codable, Hashable {

    public static let reasonRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var decision: RefundDecision
    public var whoBearsCost: WhoBearsCost?
    public var reason: String

    public init(decision: RefundDecision, whoBearsCost: WhoBearsCost? = nil, reason: String) {
        self.decision = decision
        self.whoBearsCost = whoBearsCost
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case decision
        case whoBearsCost = "who_bears_cost"
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(decision, forKey: .decision)
        try container.encodeIfPresent(whoBearsCost, forKey: .whoBearsCost)
        try container.encode(reason, forKey: .reason)
    }
}

