//
// RefundStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RefundStatus: String, Sendable, Codable, CaseIterable {
    case pending = "pending"
    case approved = "approved"
    case rejected = "rejected"
    case escalatedToAdmin = "escalated_to_admin"
}
