//
// RefundResolveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefundResolveRequest: Sendable, Codable, Hashable {

    public static let reasonRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var whoBearsCost: WhoBearsCost
    public var refundAmount: RefundAmount
    public var reason: String

    public init(whoBearsCost: WhoBearsCost, refundAmount: RefundAmount, reason: String) {
        self.whoBearsCost = whoBearsCost
        self.refundAmount = refundAmount
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case whoBearsCost = "who_bears_cost"
        case refundAmount = "refund_amount"
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(whoBearsCost, forKey: .whoBearsCost)
        try container.encode(refundAmount, forKey: .refundAmount)
        try container.encode(reason, forKey: .reason)
    }
}

