//
// RefundRequestCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefundRequestCreate: Sendable, Codable, Hashable {

    public var reasonCode: RefundReasonCode
    public var reasonText: String?
    public var evidenceUrls: [String]?
    public var refundAmount: RefundAmount1?

    public init(reasonCode: RefundReasonCode, reasonText: String? = nil, evidenceUrls: [String]? = nil, refundAmount: RefundAmount1? = nil) {
        self.reasonCode = reasonCode
        self.reasonText = reasonText
        self.evidenceUrls = evidenceUrls
        self.refundAmount = refundAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reasonCode = "reason_code"
        case reasonText = "reason_text"
        case evidenceUrls = "evidence_urls"
        case refundAmount = "refund_amount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reasonCode, forKey: .reasonCode)
        try container.encodeIfPresent(reasonText, forKey: .reasonText)
        try container.encodeIfPresent(evidenceUrls, forKey: .evidenceUrls)
        try container.encodeIfPresent(refundAmount, forKey: .refundAmount)
    }
}

