//
// ResolveReconciliationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResolveReconciliationRequest: Sendable, Codable, Hashable {

    public static let resolutionNoteRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var resolutionNote: String

    public init(resolutionNote: String) {
        self.resolutionNote = resolutionNote
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resolutionNote = "resolution_note"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resolutionNote, forKey: .resolutionNote)
    }
}

