//
// RoleRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RoleRead: Sendable, Codable, Hashable {

    public var id: Int
    public var name: String
    public var description: String?
    public var isProtected: Bool? = false
    public var permissions: [PermissionRead]?

    public init(id: Int, name: String, description: String? = nil, isProtected: Bool? = false, permissions: [PermissionRead]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.isProtected = isProtected
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case isProtected = "is_protected"
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isProtected, forKey: .isProtected)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }
}


extension RoleRead: Identifiable {}
