//
// SellerStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SellerStatus: String, Sendable, Codable, CaseIterable {
    case pendingReview = "pending_review"
    case active = "active"
    case suspended = "suspended"
    case banned = "banned"
    case rejected = "rejected"
}
