//
// SellerUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PATCH /seller/me — send only what changes. */
public struct SellerUpdateRequest: Sendable, Codable, Hashable {

    public static let interestCategoryIdsRule = ArrayRule(minItems: nil, maxItems: 50, uniqueItems: false)
    public var interestCategoryIds: [Int]?

    public init(interestCategoryIds: [Int]? = nil) {
        self.interestCategoryIds = interestCategoryIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case interestCategoryIds = "interest_category_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(interestCategoryIds, forKey: .interestCategoryIds)
    }
}

