//
// ShipmentRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ShipmentRead: Sendable, Codable, Hashable {

    public var id: Int
    public var pickupPointId: Int
    public var shopId: Int
    public var status: PickupPointShipmentStatus
    public var dispatchedAt: Date?
    public var expectedArrivalAt: Date?
    public var arrivedAt: Date?
    public var receivedByStaffId: Int?
    public var createdAt: Date
    public var items: [ShipmentItemRead]?

    public init(id: Int, pickupPointId: Int, shopId: Int, status: PickupPointShipmentStatus, dispatchedAt: Date?, expectedArrivalAt: Date?, arrivedAt: Date?, receivedByStaffId: Int?, createdAt: Date, items: [ShipmentItemRead]? = nil) {
        self.id = id
        self.pickupPointId = pickupPointId
        self.shopId = shopId
        self.status = status
        self.dispatchedAt = dispatchedAt
        self.expectedArrivalAt = expectedArrivalAt
        self.arrivedAt = arrivedAt
        self.receivedByStaffId = receivedByStaffId
        self.createdAt = createdAt
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case pickupPointId = "pickup_point_id"
        case shopId = "shop_id"
        case status
        case dispatchedAt = "dispatched_at"
        case expectedArrivalAt = "expected_arrival_at"
        case arrivedAt = "arrived_at"
        case receivedByStaffId = "received_by_staff_id"
        case createdAt = "created_at"
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(pickupPointId, forKey: .pickupPointId)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(status, forKey: .status)
        try container.encode(dispatchedAt, forKey: .dispatchedAt)
        try container.encode(expectedArrivalAt, forKey: .expectedArrivalAt)
        try container.encode(arrivedAt, forKey: .arrivedAt)
        try container.encode(receivedByStaffId, forKey: .receivedByStaffId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(items, forKey: .items)
    }
}


extension ShipmentRead: Identifiable {}
