//
// ShippingAddressIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Minimal structured shape for the JSON snapshot stored on Order — Doc 04 explicitly leaves a full address-book system out of scope, but a raw untyped dict gives the frontend no contract to build a form against. */
public struct ShippingAddressIn: Sendable, Codable, Hashable {

    public var fullName: String
    public var phone: String
    public var addressLine: String
    public var city: String
    public var region: String?
    public var postalCode: String?
    public var notes: String?

    public init(fullName: String, phone: String, addressLine: String, city: String, region: String? = nil, postalCode: String? = nil, notes: String? = nil) {
        self.fullName = fullName
        self.phone = phone
        self.addressLine = addressLine
        self.city = city
        self.region = region
        self.postalCode = postalCode
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullName = "full_name"
        case phone
        case addressLine = "address_line"
        case city
        case region
        case postalCode = "postal_code"
        case notes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fullName, forKey: .fullName)
        try container.encode(phone, forKey: .phone)
        try container.encode(addressLine, forKey: .addressLine)
        try container.encode(city, forKey: .city)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(postalCode, forKey: .postalCode)
        try container.encodeIfPresent(notes, forKey: .notes)
    }
}

