//
// ShopUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PATCH: omitted fields are unchanged. &#x60;null&#x60; clears logo_key, banner_key or description; &#x60;null&#x60; for name is ignored. */
public struct ShopUpdateRequest: Sendable, Codable, Hashable {

    public var name: String?
    public var logoKey: String?
    public var bannerKey: String?
    public var description: String?

    public init(name: String? = nil, logoKey: String? = nil, bannerKey: String? = nil, description: String? = nil) {
        self.name = name
        self.logoKey = logoKey
        self.bannerKey = bannerKey
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case logoKey = "logo_key"
        case bannerKey = "banner_key"
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(logoKey, forKey: .logoKey)
        try container.encodeIfPresent(bannerKey, forKey: .bannerKey)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

