//
// ShopCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ShopCreateRequest: Sendable, Codable, Hashable {

    public static let slugRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public var name: String
    public var slug: String?
    public var logoKey: String?
    public var bannerKey: String?
    public var description: String?
    public var legalEntityOverride: Bool? = false

    public init(name: String, slug: String? = nil, logoKey: String? = nil, bannerKey: String? = nil, description: String? = nil, legalEntityOverride: Bool? = false) {
        self.name = name
        self.slug = slug
        self.logoKey = logoKey
        self.bannerKey = bannerKey
        self.description = description
        self.legalEntityOverride = legalEntityOverride
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case slug
        case logoKey = "logo_key"
        case bannerKey = "banner_key"
        case description
        case legalEntityOverride = "legal_entity_override"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(logoKey, forKey: .logoKey)
        try container.encodeIfPresent(bannerKey, forKey: .bannerKey)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(legalEntityOverride, forKey: .legalEntityOverride)
    }
}

