//
// ShopStaffRead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ShopStaffRead: Sendable, Codable, Hashable {

    public var id: Int
    public var shopId: Int
    public var userId: Int
    public var role: StaffRole
    public var createdAt: Date

    public init(id: Int, shopId: Int, userId: Int, role: StaffRole, createdAt: Date) {
        self.id = id
        self.shopId = shopId
        self.userId = userId
        self.role = role
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case shopId = "shop_id"
        case userId = "user_id"
        case role
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(userId, forKey: .userId)
        try container.encode(role, forKey: .role)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


extension ShopStaffRead: Identifiable {}
