//
// TranslationIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TranslationIn: Sendable, Codable, Hashable {

    public static let localeRule = StringRule(minLength: nil, maxLength: 10, pattern: nil)
    public var locale: String
    public var name: String
    public var description: String?

    public init(locale: String, name: String, description: String? = nil) {
        self.locale = locale
        self.name = name
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case name
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locale, forKey: .locale)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

