//
// UploadPurpose.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum UploadPurpose: String, Sendable, Codable, CaseIterable {
    case shopLogo = "shop_logo"
    case shopBanner = "shop_banner"
    case productImage = "product_image"
    case sellerDocument = "seller_document"
}
