//
// UserPasswordSet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** POST /users/{id}/password — admin sets another user&#39;s password. */
public struct UserPasswordSet: Sendable, Codable, Hashable {

    public var password: String

    public init(password: String) {
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(password, forKey: .password)
    }
}

