/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.BankOwnerType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ownerType 
 * @param accountHolderName 
 * @param bankName 
 * @param accountNumber 
 * @param shopId 
 * @param isPrimary 
 */
@Serializable

data class BankAccountCreateRequest (

    @Contextual @SerialName(value = "owner_type")
    val ownerType: BankOwnerType,

    @SerialName(value = "account_holder_name")
    val accountHolderName: kotlin.String,

    @SerialName(value = "bank_name")
    val bankName: kotlin.String,

    @SerialName(value = "account_number")
    val accountNumber: kotlin.String,

    @SerialName(value = "shop_id")
    val shopId: kotlin.Int? = null,

    @SerialName(value = "is_primary")
    val isPrimary: kotlin.Boolean? = false

) {


}

