/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.CartItemRead

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param buyerId 
 * @param status 
 * @param createdAt 
 * @param updatedAt 
 * @param items 
 */
@Serializable

data class CartRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "buyer_id")
    val buyerId: kotlin.Int,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "items")
    val items: kotlin.collections.List<CartItemRead>? = null

) {


}

