/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.CartProductRead
import com.emarketseller.sdk.model.CartVariantRead
import com.emarketseller.sdk.model.ShopSummaryRead

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param quantity 
 * @param addedAt 
 * @param product 
 * @param variant 
 * @param shop 
 * @param priceSnapshot 
 * @param unitPrice 
 * @param lineTotal 
 * @param available 
 * @param inStock 
 */
@Serializable

data class CartItemRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "quantity")
    val quantity: kotlin.Int,

    @Contextual @SerialName(value = "added_at")
    val addedAt: java.time.OffsetDateTime,

    @SerialName(value = "product")
    val product: CartProductRead,

    @SerialName(value = "variant")
    val variant: CartVariantRead?,

    @SerialName(value = "shop")
    val shop: ShopSummaryRead,

    @SerialName(value = "price_snapshot")
    val priceSnapshot: kotlin.String,

    @SerialName(value = "unit_price")
    val unitPrice: kotlin.String,

    @SerialName(value = "line_total")
    val lineTotal: kotlin.String,

    @SerialName(value = "available")
    val available: kotlin.Boolean,

    @SerialName(value = "in_stock")
    val inStock: kotlin.Boolean

) {


}

