/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param cashCollectionRecordId 
 * @param pickupPointHoldingItemId 
 * @param quantityCollected 
 * @param amount 
 */
@Serializable

data class CashCollectionRecordItemRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "cash_collection_record_id")
    val cashCollectionRecordId: kotlin.Int,

    @SerialName(value = "pickup_point_holding_item_id")
    val pickupPointHoldingItemId: kotlin.Int,

    @SerialName(value = "quantity_collected")
    val quantityCollected: kotlin.Int,

    @SerialName(value = "amount")
    val amount: kotlin.String

) {


}

