/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: relevance,newest,price_asc,price_desc
 */
@Serializable
enum class CatalogSort(val value: kotlin.String) {

    @SerialName(value = "relevance")
    relevance("relevance"),

    @SerialName(value = "newest")
    newest("newest"),

    @SerialName(value = "price_asc")
    price_asc("price_asc"),

    @SerialName(value = "price_desc")
    price_desc("price_desc");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CatalogSort) "$data" else null

        /**
         * Returns a valid [CatalogSort] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CatalogSort? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


