/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.AttributeDataType
import com.emarketseller.sdk.model.AttributeTranslationRead

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * An effective attribute (inherited ones included) as the storefront sees it.
 *
 * @param id 
 * @param key 
 * @param dataType 
 * @param options 
 * @param unit 
 * @param isFilterable 
 * @param isVariantDefining 
 * @param sortOrder 
 * @param translations 
 */
@Serializable

data class CategoryAttributePublicRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "key")
    val key: kotlin.String,

    @Contextual @SerialName(value = "data_type")
    val dataType: AttributeDataType,

    @SerialName(value = "options")
    val options: kotlin.collections.List<kotlin.String>?,

    @SerialName(value = "unit")
    val unit: kotlin.String?,

    @SerialName(value = "is_filterable")
    val isFilterable: kotlin.Boolean,

    @SerialName(value = "is_variant_defining")
    val isVariantDefining: kotlin.Boolean,

    @SerialName(value = "sort_order")
    val sortOrder: kotlin.Int,

    @SerialName(value = "translations")
    val translations: kotlin.collections.List<AttributeTranslationRead>? = null

) {


}

