/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.TranslationIn

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param slug 
 * @param translations 
 * @param parentId 
 * @param iconUrl 
 * @param sortOrder 
 * @param requiresDocuments 
 * @param requiredDocumentTypes 
 * @param allowsVariants 
 * @param returnWindowDays 
 */
@Serializable

data class CategoryCreate (

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @SerialName(value = "translations")
    val translations: kotlin.collections.List<TranslationIn>,

    @SerialName(value = "parent_id")
    val parentId: kotlin.Int? = null,

    @SerialName(value = "icon_url")
    val iconUrl: kotlin.String? = null,

    @SerialName(value = "sort_order")
    val sortOrder: kotlin.Int? = 0,

    @SerialName(value = "requires_documents")
    val requiresDocuments: kotlin.Boolean? = false,

    @SerialName(value = "required_document_types")
    val requiredDocumentTypes: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "allows_variants")
    val allowsVariants: kotlin.Boolean? = true,

    @SerialName(value = "return_window_days")
    val returnWindowDays: kotlin.Int? = null

) {


}

