/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.AttributeDataType
import com.emarketseller.sdk.model.AttributeTranslationIn

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param key 
 * @param dataType 
 * @param translations 
 * @param options 
 * @param unit 
 * @param isRequired 
 * @param isFilterable 
 * @param isInherited 
 * @param isVariantDefining 
 * @param sortOrder 
 */
@Serializable

data class CategoryAttributeIn (

    @SerialName(value = "key")
    val key: kotlin.String,

    @Contextual @SerialName(value = "data_type")
    val dataType: AttributeDataType,

    @SerialName(value = "translations")
    val translations: kotlin.collections.List<AttributeTranslationIn>,

    @SerialName(value = "options")
    val options: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "unit")
    val unit: kotlin.String? = null,

    @SerialName(value = "is_required")
    val isRequired: kotlin.Boolean? = false,

    @SerialName(value = "is_filterable")
    val isFilterable: kotlin.Boolean? = false,

    @SerialName(value = "is_inherited")
    val isInherited: kotlin.Boolean? = false,

    @SerialName(value = "is_variant_defining")
    val isVariantDefining: kotlin.Boolean? = false,

    @SerialName(value = "sort_order")
    val sortOrder: kotlin.Int? = 0

) {


}

