/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.PaymentMethod
import com.emarketseller.sdk.model.Recipient

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param recipient 
 * @param pickupPointId 
 * @param paymentMethod 
 */
@Serializable

data class CheckoutRequest (

    @SerialName(value = "recipient")
    val recipient: Recipient,

    @SerialName(value = "pickup_point_id")
    val pickupPointId: kotlin.Int,

    @Contextual @SerialName(value = "payment_method")
    val paymentMethod: PaymentMethod

) {


}

