/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.CommissionCalculationType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ruleId 
 * @param calculationType 
 * @param percent 
 * @param flatFeeAmount 
 * @param currency 
 * @param amount 
 */
@Serializable

data class CommissionResolutionRead (

    @SerialName(value = "rule_id")
    val ruleId: kotlin.Int,

    @Contextual @SerialName(value = "calculation_type")
    val calculationType: CommissionCalculationType,

    @SerialName(value = "percent")
    val percent: kotlin.String?,

    @SerialName(value = "flat_fee_amount")
    val flatFeeAmount: kotlin.String?,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @SerialName(value = "amount")
    val amount: kotlin.String? = null

) {


}

