/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.PickupPointShipmentItemStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param itemId 
 * @param resolvedQuantity 
 * @param status 
 */
@Serializable

data class DiscrepancyItemResolution (

    @SerialName(value = "item_id")
    val itemId: kotlin.Int,

    @SerialName(value = "resolved_quantity")
    val resolvedQuantity: kotlin.Int,

    @Contextual @SerialName(value = "status")
    val status: PickupPointShipmentItemStatus

) {


}

