/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.DocumentStatus
import com.emarketseller.sdk.model.DocumentType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param sellerId 
 * @param shopId 
 * @param type 
 * @param fileKey 
 * @param status 
 * @param rejectionReason 
 * @param reviewedBy 
 * @param reviewedAt 
 * @param createdAt 
 * @param fileUrl Signed, time-limited link (STORAGE_PRESIGNED_URL_EXPIRE_SECONDS) — documents live in the private bucket. Fetch a fresh one to view again.
 */
@Serializable

data class DocumentRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "seller_id")
    val sellerId: kotlin.Int,

    @SerialName(value = "shop_id")
    val shopId: kotlin.Int?,

    @Contextual @SerialName(value = "type")
    val type: DocumentType,

    @SerialName(value = "file_key")
    val fileKey: kotlin.String,

    @Contextual @SerialName(value = "status")
    val status: DocumentStatus,

    @SerialName(value = "rejection_reason")
    val rejectionReason: kotlin.String?,

    @SerialName(value = "reviewed_by")
    val reviewedBy: kotlin.Int?,

    @Contextual @SerialName(value = "reviewed_at")
    val reviewedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Signed, time-limited link (STORAGE_PRESIGNED_URL_EXPIRE_SECONDS) — documents live in the private bucket. Fetch a fresh one to view again. */
    @SerialName(value = "file_url")
    val fileUrl: kotlin.String

) {


}

