/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.PickupPointHoldingItemStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param pickupPointHoldingId 
 * @param orderLineId 
 * @param quantity 
 * @param quantityCollected 
 * @param status 
 * @param updatedAt 
 */
@Serializable

data class HoldingItemRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "pickup_point_holding_id")
    val pickupPointHoldingId: kotlin.Int,

    @SerialName(value = "order_line_id")
    val orderLineId: kotlin.Int,

    @SerialName(value = "quantity")
    val quantity: kotlin.Int,

    @SerialName(value = "quantity_collected")
    val quantityCollected: kotlin.Int,

    @Contextual @SerialName(value = "status")
    val status: PickupPointHoldingItemStatus,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

