/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Owned by RefundService (Doc 04 §3.1a).
 *
 * Values: active,return_pending,refunded
 */
@Serializable
enum class OrderLineStatus(val value: kotlin.String) {

    @SerialName(value = "active")
    active("active"),

    @SerialName(value = "return_pending")
    return_pending("return_pending"),

    @SerialName(value = "refunded")
    refunded("refunded");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OrderLineStatus) "$data" else null

        /**
         * Returns a valid [OrderLineStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OrderLineStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


