/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: pending,confirmed,preparing,at_warehouse,shipped,delivered,cancelled,return_requested,partially_refunded,refunded,arrived_at_point,partially_collected,rejected_by_buyer,return_to_seller
 */
@Serializable
enum class OrderShopGroupStatus(val value: kotlin.String) {

    @SerialName(value = "pending")
    pending("pending"),

    @SerialName(value = "confirmed")
    confirmed("confirmed"),

    @SerialName(value = "preparing")
    preparing("preparing"),

    @SerialName(value = "at_warehouse")
    at_warehouse("at_warehouse"),

    @SerialName(value = "shipped")
    shipped("shipped"),

    @SerialName(value = "delivered")
    delivered("delivered"),

    @SerialName(value = "cancelled")
    cancelled("cancelled"),

    @SerialName(value = "return_requested")
    return_requested("return_requested"),

    @SerialName(value = "partially_refunded")
    partially_refunded("partially_refunded"),

    @SerialName(value = "refunded")
    refunded("refunded"),

    @SerialName(value = "arrived_at_point")
    arrived_at_point("arrived_at_point"),

    @SerialName(value = "partially_collected")
    partially_collected("partially_collected"),

    @SerialName(value = "rejected_by_buyer")
    rejected_by_buyer("rejected_by_buyer"),

    @SerialName(value = "return_to_seller")
    return_to_seller("return_to_seller");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OrderShopGroupStatus) "$data" else null

        /**
         * Returns a valid [OrderShopGroupStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OrderShopGroupStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


