/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.PickupPointStatus
import com.emarketseller.sdk.model.PickupPointType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param address 
 * @param latitude 
 * @param longitude 
 * @param type 
 * @param capacityUnits 
 * @param status 
 * @param operatingHours 
 * @param contactPhone 
 * @param regionId 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class PickupPointRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "address")
    val address: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @SerialName(value = "latitude")
    val latitude: kotlin.String,

    @SerialName(value = "longitude")
    val longitude: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: PickupPointType,

    @SerialName(value = "capacity_units")
    val capacityUnits: kotlin.Int?,

    @Contextual @SerialName(value = "status")
    val status: PickupPointStatus,

    @Contextual @SerialName(value = "operating_hours")
    val operatingHours: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @SerialName(value = "contact_phone")
    val contactPhone: kotlin.String,

    @SerialName(value = "region_id")
    val regionId: kotlin.Int,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

