/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.PickupPointStaffRole
import com.emarketseller.sdk.model.PickupPointStaffStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param pickupPointId 
 * @param userId 
 * @param role 
 * @param status 
 * @param createdAt 
 */
@Serializable

data class PickupPointStaffRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "pickup_point_id")
    val pickupPointId: kotlin.Int,

    @SerialName(value = "user_id")
    val userId: kotlin.Int,

    @Contextual @SerialName(value = "role")
    val role: PickupPointStaffRole,

    @Contextual @SerialName(value = "status")
    val status: PickupPointStaffStatus,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}

