/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.CategoryAncestorRead
import com.emarketseller.sdk.model.TranslationRead

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param slug 
 * @param translations 
 * @param ancestors 
 */
@Serializable

data class ProductCategoryRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @SerialName(value = "translations")
    val translations: kotlin.collections.List<TranslationRead>? = null,

    @SerialName(value = "ancestors")
    val ancestors: kotlin.collections.List<CategoryAncestorRead>? = null

) {


}

