/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.AttributesValue

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param platformSku 
 * @param price 
 * @param inStock 
 * @param attributes 
 * @param imageIds 
 */
@Serializable

data class ProductPublicVariantRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "platform_sku")
    val platformSku: kotlin.String,

    @SerialName(value = "price")
    val price: kotlin.String,

    @SerialName(value = "in_stock")
    val inStock: kotlin.Boolean,

    @Contextual @SerialName(value = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, AttributesValue>,

    @SerialName(value = "image_ids")
    val imageIds: kotlin.collections.List<kotlin.Int>?

) {


}

