/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.BasePrice
import com.emarketseller.sdk.model.ProductAttributeValueIn
import com.emarketseller.sdk.model.ProductImageIn

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param categoryId 
 * @param title 
 * @param slug 
 * @param brandId 
 * @param description 
 * @param hasVariants 
 * @param basePrice 
 * @param stockQuantity 
 * @param sellerSku 
 * @param images 
 * @param attributeValues 
 */
@Serializable

data class ProductCreate (

    @SerialName(value = "category_id")
    val categoryId: kotlin.Int,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @SerialName(value = "brand_id")
    val brandId: kotlin.Int? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "has_variants")
    val hasVariants: kotlin.Boolean? = false,

    @SerialName(value = "base_price")
    val basePrice: BasePrice? = null,

    @SerialName(value = "stock_quantity")
    val stockQuantity: kotlin.Int? = null,

    @SerialName(value = "seller_sku")
    val sellerSku: kotlin.String? = null,

    @SerialName(value = "images")
    val images: kotlin.collections.List<ProductImageIn>? = null,

    @SerialName(value = "attribute_values")
    val attributeValues: kotlin.collections.List<ProductAttributeValueIn>? = null

) {


}

