/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.ModerationAction

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param productId 
 * @param action 
 * @param adminId 
 * @param reason 
 * @param snapshot 
 * @param createdAt 
 */
@Serializable

data class ProductModerationLogRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "product_id")
    val productId: kotlin.Int,

    @Contextual @SerialName(value = "action")
    val action: ModerationAction,

    @SerialName(value = "admin_id")
    val adminId: kotlin.Int?,

    @SerialName(value = "reason")
    val reason: kotlin.String?,

    @Contextual @SerialName(value = "snapshot")
    val snapshot: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}

