/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.OrderPickupPointRead
import com.emarketseller.sdk.model.RefundReasonCode
import com.emarketseller.sdk.model.RefundStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A line's latest refund request, as the buyer's order page needs it.
 *
 * @param id 
 * @param status 
 * @param reasonCode 
 * @param createdAt 
 * @param resolvedAt 
 * @param escalatedAt 
 * @param resolutionNote 
 * @param returnPoint 
 * @param pointReceivedAt 
 */
@Serializable

data class RefundRequestSummaryRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @Contextual @SerialName(value = "status")
    val status: RefundStatus,

    @Contextual @SerialName(value = "reason_code")
    val reasonCode: RefundReasonCode,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "resolved_at")
    val resolvedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "escalated_at")
    val escalatedAt: java.time.OffsetDateTime?,

    @SerialName(value = "resolution_note")
    val resolutionNote: kotlin.String?,

    @SerialName(value = "return_point")
    val returnPoint: OrderPickupPointRead?,

    @Contextual @SerialName(value = "point_received_at")
    val pointReceivedAt: java.time.OffsetDateTime?

) {


}

