/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.RefundAmount1
import com.emarketseller.sdk.model.RefundReasonCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param reasonCode 
 * @param reasonText 
 * @param evidenceUrls 
 * @param refundAmount 
 */
@Serializable

data class RefundRequestCreate (

    @Contextual @SerialName(value = "reason_code")
    val reasonCode: RefundReasonCode,

    @SerialName(value = "reason_text")
    val reasonText: kotlin.String? = null,

    @SerialName(value = "evidence_urls")
    val evidenceUrls: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "refund_amount")
    val refundAmount: RefundAmount1? = null

) {


}

