/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.EntityType
import com.emarketseller.sdk.model.SellerStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param legalName 
 * @param entityType 
 * @param taxId 
 * @param country 
 * @param contactEmail 
 * @param contactPhone 
 * @param status 
 * @param statusReason 
 * @param shopLimit 
 * @param riskScore 
 * @param verifiedAt 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class SellerRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "user_id")
    val userId: kotlin.Int,

    @SerialName(value = "legal_name")
    val legalName: kotlin.String,

    @Contextual @SerialName(value = "entity_type")
    val entityType: EntityType,

    @SerialName(value = "tax_id")
    val taxId: kotlin.String,

    @SerialName(value = "country")
    val country: kotlin.String,

    @SerialName(value = "contact_email")
    val contactEmail: kotlin.String,

    @SerialName(value = "contact_phone")
    val contactPhone: kotlin.String?,

    @Contextual @SerialName(value = "status")
    val status: SellerStatus,

    @SerialName(value = "status_reason")
    val statusReason: kotlin.String?,

    @SerialName(value = "shop_limit")
    val shopLimit: kotlin.Int,

    @SerialName(value = "risk_score")
    val riskScore: kotlin.Int?,

    @Contextual @SerialName(value = "verified_at")
    val verifiedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

