/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param logoUrl 
 * @param bannerUrl 
 * @param description 
 */
@Serializable

data class ShopUpdateRequest (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "logo_url")
    val logoUrl: kotlin.String? = null,

    @SerialName(value = "banner_url")
    val bannerUrl: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

