/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import com.emarketseller.sdk.model.UploadPurpose

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param key 
 * @param url 
 * @param purpose 
 * @param contentType 
 * @param sizeBytes 
 * @param width 
 * @param height 
 * @param createdAt 
 */
@Serializable

data class UploadRead (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "key")
    val key: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @Contextual @SerialName(value = "purpose")
    val purpose: UploadPurpose,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Int,

    @SerialName(value = "width")
    val width: kotlin.Int?,

    @SerialName(value = "height")
    val height: kotlin.Int?,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}

