/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: shop_logo,shop_banner,product_image,seller_document
 */
@Serializable
enum class UploadPurpose(val value: kotlin.String) {

    @SerialName(value = "shop_logo")
    shop_logo("shop_logo"),

    @SerialName(value = "shop_banner")
    shop_banner("shop_banner"),

    @SerialName(value = "product_image")
    product_image("product_image"),

    @SerialName(value = "seller_document")
    seller_document("seller_document");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UploadPurpose) "$data" else null

        /**
         * Returns a valid [UploadPurpose] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UploadPurpose? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


