/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.CashCollectionRecordItemRead

class CashCollectionRecordItemReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CashCollectionRecordItemRead
        //val modelInstance = CashCollectionRecordItemRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `cashCollectionRecordId`
        should("test cashCollectionRecordId") {
            // uncomment below to test the property
            //modelInstance.cashCollectionRecordId shouldBe ("TODO")
        }

        // to test the property `pickupPointHoldingItemId`
        should("test pickupPointHoldingItemId") {
            // uncomment below to test the property
            //modelInstance.pickupPointHoldingItemId shouldBe ("TODO")
        }

        // to test the property `quantityCollected`
        should("test quantityCollected") {
            // uncomment below to test the property
            //modelInstance.quantityCollected shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

    }
}
