/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.CashCollectionRecordRead
import com.emarketseller.sdk.model.CashCollectionRecordItemRead

class CashCollectionRecordReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CashCollectionRecordRead
        //val modelInstance = CashCollectionRecordRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `orderShopGroupId`
        should("test orderShopGroupId") {
            // uncomment below to test the property
            //modelInstance.orderShopGroupId shouldBe ("TODO")
        }

        // to test the property `amountCollected`
        should("test amountCollected") {
            // uncomment below to test the property
            //modelInstance.amountCollected shouldBe ("TODO")
        }

        // to test the property `collectedByStaffId`
        should("test collectedByStaffId") {
            // uncomment below to test the property
            //modelInstance.collectedByStaffId shouldBe ("TODO")
        }

        // to test the property `collectedAt`
        should("test collectedAt") {
            // uncomment below to test the property
            //modelInstance.collectedAt shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
