/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.CategoryAssignmentRead
import com.emarketseller.sdk.model.CategoryAssignmentStatus

class CategoryAssignmentReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryAssignmentRead
        //val modelInstance = CategoryAssignmentRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `shopId`
        should("test shopId") {
            // uncomment below to test the property
            //modelInstance.shopId shouldBe ("TODO")
        }

        // to test the property `categoryId`
        should("test categoryId") {
            // uncomment below to test the property
            //modelInstance.categoryId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `documentIds`
        should("test documentIds") {
            // uncomment below to test the property
            //modelInstance.documentIds shouldBe ("TODO")
        }

        // to test the property `rejectionReason`
        should("test rejectionReason") {
            // uncomment below to test the property
            //modelInstance.rejectionReason shouldBe ("TODO")
        }

        // to test the property `needsReverification`
        should("test needsReverification") {
            // uncomment below to test the property
            //modelInstance.needsReverification shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
