/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.CollectItemInput

class CollectItemInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CollectItemInput
        //val modelInstance = CollectItemInput()

        // to test the property `holdingItemId`
        should("test holdingItemId") {
            // uncomment below to test the property
            //modelInstance.holdingItemId shouldBe ("TODO")
        }

        // to test the property `quantityCollected`
        should("test quantityCollected") {
            // uncomment below to test the property
            //modelInstance.quantityCollected shouldBe ("TODO")
        }

    }
}
