/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.CommissionResolutionRead
import com.emarketseller.sdk.model.CommissionCalculationType

class CommissionResolutionReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CommissionResolutionRead
        //val modelInstance = CommissionResolutionRead()

        // to test the property `ruleId`
        should("test ruleId") {
            // uncomment below to test the property
            //modelInstance.ruleId shouldBe ("TODO")
        }

        // to test the property `calculationType`
        should("test calculationType") {
            // uncomment below to test the property
            //modelInstance.calculationType shouldBe ("TODO")
        }

        // to test the property `percent`
        should("test percent") {
            // uncomment below to test the property
            //modelInstance.percent shouldBe ("TODO")
        }

        // to test the property `flatFeeAmount`
        should("test flatFeeAmount") {
            // uncomment below to test the property
            //modelInstance.flatFeeAmount shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

    }
}
