/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.LedgerStatementRead
import com.emarketseller.sdk.model.LedgerEntryRead

class LedgerStatementReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LedgerStatementRead
        //val modelInstance = LedgerStatementRead()

        // to test the property `shopId`
        should("test shopId") {
            // uncomment below to test the property
            //modelInstance.shopId shouldBe ("TODO")
        }

        // to test the property `periodStart`
        should("test periodStart") {
            // uncomment below to test the property
            //modelInstance.periodStart shouldBe ("TODO")
        }

        // to test the property `periodEnd`
        should("test periodEnd") {
            // uncomment below to test the property
            //modelInstance.periodEnd shouldBe ("TODO")
        }

        // to test the property `balance`
        should("test balance") {
            // uncomment below to test the property
            //modelInstance.balance shouldBe ("TODO")
        }

        // to test the property `propertyEntries`
        should("test propertyEntries") {
            // uncomment below to test the property
            //modelInstance.propertyEntries shouldBe ("TODO")
        }

    }
}
