/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.OrderRead
import com.emarketseller.sdk.model.OrderShopGroupRead
import com.emarketseller.sdk.model.OrderStatus
import com.emarketseller.sdk.model.PaymentMethod

class OrderReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderRead
        //val modelInstance = OrderRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `buyerId`
        should("test buyerId") {
            // uncomment below to test the property
            //modelInstance.buyerId shouldBe ("TODO")
        }

        // to test the property `orderNumber`
        should("test orderNumber") {
            // uncomment below to test the property
            //modelInstance.orderNumber shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `totalAmount`
        should("test totalAmount") {
            // uncomment below to test the property
            //modelInstance.totalAmount shouldBe ("TODO")
        }

        // to test the property `shippingAddress`
        should("test shippingAddress") {
            // uncomment below to test the property
            //modelInstance.shippingAddress shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `paymentReference`
        should("test paymentReference") {
            // uncomment below to test the property
            //modelInstance.paymentReference shouldBe ("TODO")
        }

        // to test the property `placedAt`
        should("test placedAt") {
            // uncomment below to test the property
            //modelInstance.placedAt shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `groups`
        should("test groups") {
            // uncomment below to test the property
            //modelInstance.groups shouldBe ("TODO")
        }

    }
}
