/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.OrderShopGroupBase
import com.emarketseller.sdk.model.OrderShopGroupStatus

class OrderShopGroupBaseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderShopGroupBase
        //val modelInstance = OrderShopGroupBase()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `orderId`
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `shopId`
        should("test shopId") {
            // uncomment below to test the property
            //modelInstance.shopId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `subtotal`
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

        // to test the property `shippingFee`
        should("test shippingFee") {
            // uncomment below to test the property
            //modelInstance.shippingFee shouldBe ("TODO")
        }

        // to test the property `cancellationReason`
        should("test cancellationReason") {
            // uncomment below to test the property
            //modelInstance.cancellationReason shouldBe ("TODO")
        }

        // to test the property `warehouseReceivedAt`
        should("test warehouseReceivedAt") {
            // uncomment below to test the property
            //modelInstance.warehouseReceivedAt shouldBe ("TODO")
        }

        // to test the property `deliveredAt`
        should("test deliveredAt") {
            // uncomment below to test the property
            //modelInstance.deliveredAt shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
