/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.PickupReturnRead
import com.emarketseller.sdk.model.RefundReasonCode

class PickupReturnReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PickupReturnRead
        //val modelInstance = PickupReturnRead()

        // to test the property `refundRequestId`
        should("test refundRequestId") {
            // uncomment below to test the property
            //modelInstance.refundRequestId shouldBe ("TODO")
        }

        // to test the property `orderId`
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `orderNumber`
        should("test orderNumber") {
            // uncomment below to test the property
            //modelInstance.orderNumber shouldBe ("TODO")
        }

        // to test the property `recipientName`
        should("test recipientName") {
            // uncomment below to test the property
            //modelInstance.recipientName shouldBe ("TODO")
        }

        // to test the property `recipientPhone`
        should("test recipientPhone") {
            // uncomment below to test the property
            //modelInstance.recipientPhone shouldBe ("TODO")
        }

        // to test the property `productTitle`
        should("test productTitle") {
            // uncomment below to test the property
            //modelInstance.productTitle shouldBe ("TODO")
        }

        // to test the property `platformSku`
        should("test platformSku") {
            // uncomment below to test the property
            //modelInstance.platformSku shouldBe ("TODO")
        }

        // to test the property `quantity`
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `reasonCode`
        should("test reasonCode") {
            // uncomment below to test the property
            //modelInstance.reasonCode shouldBe ("TODO")
        }

        // to test the property `reasonText`
        should("test reasonText") {
            // uncomment below to test the property
            //modelInstance.reasonText shouldBe ("TODO")
        }

        // to test the property `approvedAt`
        should("test approvedAt") {
            // uncomment below to test the property
            //modelInstance.approvedAt shouldBe ("TODO")
        }

    }
}
