/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.PickupStatusItemRead
import com.emarketseller.sdk.model.PickupPointHoldingItemStatus

class PickupStatusItemReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PickupStatusItemRead
        //val modelInstance = PickupStatusItemRead()

        // to test the property `orderLineId`
        should("test orderLineId") {
            // uncomment below to test the property
            //modelInstance.orderLineId shouldBe ("TODO")
        }

        // to test the property `quantity`
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `quantityCollected`
        should("test quantityCollected") {
            // uncomment below to test the property
            //modelInstance.quantityCollected shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
