/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.PickupStatusRead
import com.emarketseller.sdk.model.PickupPointHoldingStatus
import com.emarketseller.sdk.model.PickupStatusItemRead

class PickupStatusReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PickupStatusRead
        //val modelInstance = PickupStatusRead()

        // to test the property `orderShopGroupId`
        should("test orderShopGroupId") {
            // uncomment below to test the property
            //modelInstance.orderShopGroupId shouldBe ("TODO")
        }

        // to test the property `pickupPointId`
        should("test pickupPointId") {
            // uncomment below to test the property
            //modelInstance.pickupPointId shouldBe ("TODO")
        }

        // to test the property `holdingStatus`
        should("test holdingStatus") {
            // uncomment below to test the property
            //modelInstance.holdingStatus shouldBe ("TODO")
        }

        // to test the property `arrivedAt`
        should("test arrivedAt") {
            // uncomment below to test the property
            //modelInstance.arrivedAt shouldBe ("TODO")
        }

        // to test the property `collectionDeadline`
        should("test collectionDeadline") {
            // uncomment below to test the property
            //modelInstance.collectionDeadline shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
