/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.PickupPointCreateRequest
import com.emarketseller.sdk.model.Latitude
import com.emarketseller.sdk.model.Longitude
import com.emarketseller.sdk.model.PickupPointType

class PickupPointCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PickupPointCreateRequest
        //val modelInstance = PickupPointCreateRequest()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `operatingHours`
        should("test operatingHours") {
            // uncomment below to test the property
            //modelInstance.operatingHours shouldBe ("TODO")
        }

        // to test the property `contactPhone`
        should("test contactPhone") {
            // uncomment below to test the property
            //modelInstance.contactPhone shouldBe ("TODO")
        }

        // to test the property `regionId`
        should("test regionId") {
            // uncomment below to test the property
            //modelInstance.regionId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `capacityUnits`
        should("test capacityUnits") {
            // uncomment below to test the property
            //modelInstance.capacityUnits shouldBe ("TODO")
        }

    }
}
