/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.ProductRead
import com.emarketseller.sdk.model.ProductAttributeValueRead
import com.emarketseller.sdk.model.ProductImageRead
import com.emarketseller.sdk.model.ProductStatus
import com.emarketseller.sdk.model.ProductVariantRead

class ProductReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductRead
        //val modelInstance = ProductRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `shopId`
        should("test shopId") {
            // uncomment below to test the property
            //modelInstance.shopId shouldBe ("TODO")
        }

        // to test the property `categoryId`
        should("test categoryId") {
            // uncomment below to test the property
            //modelInstance.categoryId shouldBe ("TODO")
        }

        // to test the property `brandId`
        should("test brandId") {
            // uncomment below to test the property
            //modelInstance.brandId shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `hasVariants`
        should("test hasVariants") {
            // uncomment below to test the property
            //modelInstance.hasVariants shouldBe ("TODO")
        }

        // to test the property `basePrice`
        should("test basePrice") {
            // uncomment below to test the property
            //modelInstance.basePrice shouldBe ("TODO")
        }

        // to test the property `stockQuantity`
        should("test stockQuantity") {
            // uncomment below to test the property
            //modelInstance.stockQuantity shouldBe ("TODO")
        }

        // to test the property `sku`
        should("test sku") {
            // uncomment below to test the property
            //modelInstance.sku shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `rejectionReason`
        should("test rejectionReason") {
            // uncomment below to test the property
            //modelInstance.rejectionReason shouldBe ("TODO")
        }

        // to test the property `needsAttention`
        should("test needsAttention") {
            // uncomment below to test the property
            //modelInstance.needsAttention shouldBe ("TODO")
        }

        // to test the property `moderatedBy`
        should("test moderatedBy") {
            // uncomment below to test the property
            //modelInstance.moderatedBy shouldBe ("TODO")
        }

        // to test the property `moderatedAt`
        should("test moderatedAt") {
            // uncomment below to test the property
            //modelInstance.moderatedAt shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `images`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `variants`
        should("test variants") {
            // uncomment below to test the property
            //modelInstance.variants shouldBe ("TODO")
        }

        // to test the property `attributeValues`
        should("test attributeValues") {
            // uncomment below to test the property
            //modelInstance.attributeValues shouldBe ("TODO")
        }

    }
}
