/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.ProductPublicImageRead

class ProductPublicImageReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductPublicImageRead
        //val modelInstance = ProductPublicImageRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `sortOrder`
        should("test sortOrder") {
            // uncomment below to test the property
            //modelInstance.sortOrder shouldBe ("TODO")
        }

        // to test the property `isPrimary`
        should("test isPrimary") {
            // uncomment below to test the property
            //modelInstance.isPrimary shouldBe ("TODO")
        }

    }
}
