/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.ReconciliationRead
import com.emarketseller.sdk.model.PickupPointCashReconciliationStatus

class ReconciliationReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReconciliationRead
        //val modelInstance = ReconciliationRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `pickupPointId`
        should("test pickupPointId") {
            // uncomment below to test the property
            //modelInstance.pickupPointId shouldBe ("TODO")
        }

        // to test the property `periodStart`
        should("test periodStart") {
            // uncomment below to test the property
            //modelInstance.periodStart shouldBe ("TODO")
        }

        // to test the property `periodEnd`
        should("test periodEnd") {
            // uncomment below to test the property
            //modelInstance.periodEnd shouldBe ("TODO")
        }

        // to test the property `expectedAmount`
        should("test expectedAmount") {
            // uncomment below to test the property
            //modelInstance.expectedAmount shouldBe ("TODO")
        }

        // to test the property `declaredAmount`
        should("test declaredAmount") {
            // uncomment below to test the property
            //modelInstance.declaredAmount shouldBe ("TODO")
        }

        // to test the property `variance`
        should("test variance") {
            // uncomment below to test the property
            //modelInstance.variance shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `submittedByStaffId`
        should("test submittedByStaffId") {
            // uncomment below to test the property
            //modelInstance.submittedByStaffId shouldBe ("TODO")
        }

        // to test the property `reviewedBy`
        should("test reviewedBy") {
            // uncomment below to test the property
            //modelInstance.reviewedBy shouldBe ("TODO")
        }

        // to test the property `resolutionNote`
        should("test resolutionNote") {
            // uncomment below to test the property
            //modelInstance.resolutionNote shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
