/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.RefundResolveRequest
import com.emarketseller.sdk.model.RefundAmount
import com.emarketseller.sdk.model.WhoBearsCost

class RefundResolveRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RefundResolveRequest
        //val modelInstance = RefundResolveRequest()

        // to test the property `whoBearsCost`
        should("test whoBearsCost") {
            // uncomment below to test the property
            //modelInstance.whoBearsCost shouldBe ("TODO")
        }

        // to test the property `refundAmount`
        should("test refundAmount") {
            // uncomment below to test the property
            //modelInstance.refundAmount shouldBe ("TODO")
        }

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

    }
}
