/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.ResolveReconciliationRequest

class ResolveReconciliationRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResolveReconciliationRequest
        //val modelInstance = ResolveReconciliationRequest()

        // to test the property `resolutionNote`
        should("test resolutionNote") {
            // uncomment below to test the property
            //modelInstance.resolutionNote shouldBe ("TODO")
        }

    }
}
