/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.SellerAdminRead
import com.emarketseller.sdk.model.EntityType
import com.emarketseller.sdk.model.SellerStatus

class SellerAdminReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SellerAdminRead
        //val modelInstance = SellerAdminRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `legalName`
        should("test legalName") {
            // uncomment below to test the property
            //modelInstance.legalName shouldBe ("TODO")
        }

        // to test the property `entityType`
        should("test entityType") {
            // uncomment below to test the property
            //modelInstance.entityType shouldBe ("TODO")
        }

        // to test the property `taxId`
        should("test taxId") {
            // uncomment below to test the property
            //modelInstance.taxId shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `contactEmail`
        should("test contactEmail") {
            // uncomment below to test the property
            //modelInstance.contactEmail shouldBe ("TODO")
        }

        // to test the property `contactPhone`
        should("test contactPhone") {
            // uncomment below to test the property
            //modelInstance.contactPhone shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusReason`
        should("test statusReason") {
            // uncomment below to test the property
            //modelInstance.statusReason shouldBe ("TODO")
        }

        // to test the property `shopLimit`
        should("test shopLimit") {
            // uncomment below to test the property
            //modelInstance.shopLimit shouldBe ("TODO")
        }

        // to test the property `interestCategoryIds`
        should("test interestCategoryIds") {
            // uncomment below to test the property
            //modelInstance.interestCategoryIds shouldBe ("TODO")
        }

        // to test the property `riskScore`
        should("test riskScore") {
            // uncomment below to test the property
            //modelInstance.riskScore shouldBe ("TODO")
        }

        // to test the property `verifiedAt`
        should("test verifiedAt") {
            // uncomment below to test the property
            //modelInstance.verifiedAt shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `riskFlags`
        should("test riskFlags") {
            // uncomment below to test the property
            //modelInstance.riskFlags shouldBe ("TODO")
        }

    }
}
