/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.model.ShopRead
import com.emarketseller.sdk.model.ShopStatus

class ShopReadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShopRead
        //val modelInstance = ShopRead()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `sellerId`
        should("test sellerId") {
            // uncomment below to test the property
            //modelInstance.sellerId shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `logoUrl`
        should("test logoUrl") {
            // uncomment below to test the property
            //modelInstance.logoUrl shouldBe ("TODO")
        }

        // to test the property `bannerUrl`
        should("test bannerUrl") {
            // uncomment below to test the property
            //modelInstance.bannerUrl shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `legalEntityOverride`
        should("test legalEntityOverride") {
            // uncomment below to test the property
            //modelInstance.legalEntityOverride shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusReason`
        should("test statusReason") {
            // uncomment below to test the property
            //modelInstance.statusReason shouldBe ("TODO")
        }

        // to test the property `ratingAvg`
        should("test ratingAvg") {
            // uncomment below to test the property
            //modelInstance.ratingAvg shouldBe ("TODO")
        }

        // to test the property `ratingCount`
        should("test ratingCount") {
            // uncomment below to test the property
            //modelInstance.ratingCount shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
