//
// ProductsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ProductsAPI {

    /**
     Approve Brand
     
     - parameter brandId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BrandRead
     */
    open class func approveBrandApiV1AdminBrandsBrandIdApprovePatch(brandId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> BrandRead {
        return try await approveBrandApiV1AdminBrandsBrandIdApprovePatchWithRequestBuilder(brandId: brandId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Approve Brand
     - PATCH /api/v1/admin/brands/{brand_id}/approve
     - parameter brandId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BrandRead> 
     */
    open class func approveBrandApiV1AdminBrandsBrandIdApprovePatchWithRequestBuilder(brandId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<BrandRead> {
        var localVariablePath = "/api/v1/admin/brands/{brand_id}/approve"
        let brandIdPreEscape = "\(APIHelper.mapValueToPathItem(brandId))"
        let brandIdPostEscape = brandIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{brand_id}", with: brandIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BrandRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Approve Product
     
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func approveProductApiV1AdminProductsProductIdApprovePatch(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await approveProductApiV1AdminProductsProductIdApprovePatchWithRequestBuilder(productId: productId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Approve Product
     - PATCH /api/v1/admin/products/{product_id}/approve
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func approveProductApiV1AdminProductsProductIdApprovePatchWithRequestBuilder(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/admin/products/{product_id}/approve"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Archive Product
     
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func archiveProductApiV1SellerProductsProductIdArchivePost(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await archiveProductApiV1SellerProductsProductIdArchivePostWithRequestBuilder(productId: productId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Archive Product
     - POST /api/v1/seller/products/{product_id}/archive
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func archiveProductApiV1SellerProductsProductIdArchivePostWithRequestBuilder(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/seller/products/{product_id}/archive"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Create Product
     
     - parameter shopId: (path)  
     - parameter productCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func createProductApiV1SellerShopsShopIdProductsPost(shopId: Int, productCreate: ProductCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await createProductApiV1SellerShopsShopIdProductsPostWithRequestBuilder(shopId: shopId, productCreate: productCreate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create Product
     - POST /api/v1/seller/shops/{shop_id}/products
     - parameter shopId: (path)  
     - parameter productCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func createProductApiV1SellerShopsShopIdProductsPostWithRequestBuilder(shopId: Int, productCreate: ProductCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/seller/shops/{shop_id}/products"
        let shopIdPreEscape = "\(APIHelper.mapValueToPathItem(shopId))"
        let shopIdPostEscape = shopIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{shop_id}", with: shopIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: productCreate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Create Variant
     
     - parameter productId: (path)  
     - parameter productVariantCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductVariantRead
     */
    open class func createVariantApiV1SellerProductsProductIdVariantsPost(productId: Int, productVariantCreate: ProductVariantCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductVariantRead {
        return try await createVariantApiV1SellerProductsProductIdVariantsPostWithRequestBuilder(productId: productId, productVariantCreate: productVariantCreate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create Variant
     - POST /api/v1/seller/products/{product_id}/variants
     - parameter productId: (path)  
     - parameter productVariantCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductVariantRead> 
     */
    open class func createVariantApiV1SellerProductsProductIdVariantsPostWithRequestBuilder(productId: Int, productVariantCreate: ProductVariantCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductVariantRead> {
        var localVariablePath = "/api/v1/seller/products/{product_id}/variants"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: productVariantCreate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductVariantRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete Variant
     
     - parameter variantId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteVariantApiV1SellerVariantsVariantIdDelete(variantId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteVariantApiV1SellerVariantsVariantIdDeleteWithRequestBuilder(variantId: variantId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete Variant
     - DELETE /api/v1/seller/variants/{variant_id}
     - parameter variantId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteVariantApiV1SellerVariantsVariantIdDeleteWithRequestBuilder(variantId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/seller/variants/{variant_id}"
        let variantIdPreEscape = "\(APIHelper.mapValueToPathItem(variantId))"
        let variantIdPostEscape = variantIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{variant_id}", with: variantIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delist Product Admin
     
     - parameter productId: (path)  
     - parameter delistRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func delistProductAdminApiV1AdminProductsProductIdDelistPatch(productId: Int, delistRequest: DelistRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await delistProductAdminApiV1AdminProductsProductIdDelistPatchWithRequestBuilder(productId: productId, delistRequest: delistRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delist Product Admin
     - PATCH /api/v1/admin/products/{product_id}/delist
     - parameter productId: (path)  
     - parameter delistRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func delistProductAdminApiV1AdminProductsProductIdDelistPatchWithRequestBuilder(productId: Int, delistRequest: DelistRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/admin/products/{product_id}/delist"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: delistRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delist Product Seller
     
     - parameter productId: (path)  
     - parameter delistRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func delistProductSellerApiV1SellerProductsProductIdDelistPost(productId: Int, delistRequest: DelistRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await delistProductSellerApiV1SellerProductsProductIdDelistPostWithRequestBuilder(productId: productId, delistRequest: delistRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delist Product Seller
     - POST /api/v1/seller/products/{product_id}/delist
     - parameter productId: (path)  
     - parameter delistRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func delistProductSellerApiV1SellerProductsProductIdDelistPostWithRequestBuilder(productId: Int, delistRequest: DelistRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/seller/products/{product_id}/delist"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: delistRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Moderation Config
     
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ModerationConfigRead
     */
    open class func getModerationConfigApiV1AdminModerationConfigGet(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ModerationConfigRead {
        return try await getModerationConfigApiV1AdminModerationConfigGetWithRequestBuilder(accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Moderation Config
     - GET /api/v1/admin/moderation-config
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ModerationConfigRead> 
     */
    open class func getModerationConfigApiV1AdminModerationConfigGetWithRequestBuilder(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ModerationConfigRead> {
        let localVariablePath = "/api/v1/admin/moderation-config"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ModerationConfigRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Moderation Log
     
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ProductModerationLogRead]
     */
    open class func getModerationLogApiV1AdminProductsProductIdModerationLogGet(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ProductModerationLogRead] {
        return try await getModerationLogApiV1AdminProductsProductIdModerationLogGetWithRequestBuilder(productId: productId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Moderation Log
     - GET /api/v1/admin/products/{product_id}/moderation-log
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ProductModerationLogRead]> 
     */
    open class func getModerationLogApiV1AdminProductsProductIdModerationLogGetWithRequestBuilder(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[ProductModerationLogRead]> {
        var localVariablePath = "/api/v1/admin/products/{product_id}/moderation-log"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProductModerationLogRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Moderation Queue
     
     - parameter categoryId: (query)  (optional)
     - parameter shopId: (query)  (optional)
     - parameter onlyFlagged: (query)  (optional, default to false)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ModerationQueueItemRead]
     */
    open class func getModerationQueueApiV1AdminModerationQueueGet(categoryId: Int? = nil, shopId: Int? = nil, onlyFlagged: Bool? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ModerationQueueItemRead] {
        return try await getModerationQueueApiV1AdminModerationQueueGetWithRequestBuilder(categoryId: categoryId, shopId: shopId, onlyFlagged: onlyFlagged, skip: skip, limit: limit, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Moderation Queue
     - GET /api/v1/admin/moderation-queue
     - parameter categoryId: (query)  (optional)
     - parameter shopId: (query)  (optional)
     - parameter onlyFlagged: (query)  (optional, default to false)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ModerationQueueItemRead]> 
     */
    open class func getModerationQueueApiV1AdminModerationQueueGetWithRequestBuilder(categoryId: Int? = nil, shopId: Int? = nil, onlyFlagged: Bool? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[ModerationQueueItemRead]> {
        let localVariablePath = "/api/v1/admin/moderation-queue"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "category_id": (wrappedValue: categoryId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "shop_id": (wrappedValue: shopId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "only_flagged": (wrappedValue: onlyFlagged?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "skip": (wrappedValue: skip?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ModerationQueueItemRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Product Admin
     
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func getProductAdminApiV1AdminProductsProductIdGet(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await getProductAdminApiV1AdminProductsProductIdGetWithRequestBuilder(productId: productId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Product Admin
     - GET /api/v1/admin/products/{product_id}
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func getProductAdminApiV1AdminProductsProductIdGetWithRequestBuilder(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/admin/products/{product_id}"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Product Public
     
     - parameter productId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func getProductPublicApiV1ProductsProductIdGet(productId: Int, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await getProductPublicApiV1ProductsProductIdGetWithRequestBuilder(productId: productId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Product Public
     - GET /api/v1/products/{product_id}
     - parameter productId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func getProductPublicApiV1ProductsProductIdGetWithRequestBuilder(productId: Int, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/products/{product_id}"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Product Seller
     
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func getProductSellerApiV1SellerProductsProductIdGet(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await getProductSellerApiV1SellerProductsProductIdGetWithRequestBuilder(productId: productId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Product Seller
     - GET /api/v1/seller/products/{product_id}
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func getProductSellerApiV1SellerProductsProductIdGetWithRequestBuilder(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/seller/products/{product_id}"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Brands Admin
     
     - parameter status: (query)  (optional)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [BrandRead]
     */
    open class func listBrandsAdminApiV1AdminBrandsGet(status: BrandStatus? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [BrandRead] {
        return try await listBrandsAdminApiV1AdminBrandsGetWithRequestBuilder(status: status, skip: skip, limit: limit, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Brands Admin
     - GET /api/v1/admin/brands
     - parameter status: (query)  (optional)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[BrandRead]> 
     */
    open class func listBrandsAdminApiV1AdminBrandsGetWithRequestBuilder(status: BrandStatus? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[BrandRead]> {
        let localVariablePath = "/api/v1/admin/brands"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "skip": (wrappedValue: skip?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[BrandRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Brands Seller
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [BrandRead]
     */
    open class func listBrandsSellerApiV1SellerBrandsGet(apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [BrandRead] {
        return try await listBrandsSellerApiV1SellerBrandsGetWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Brands Seller
     - GET /api/v1/seller/brands
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[BrandRead]> 
     */
    open class func listBrandsSellerApiV1SellerBrandsGetWithRequestBuilder(apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[BrandRead]> {
        let localVariablePath = "/api/v1/seller/brands"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[BrandRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Products Admin
     
     - parameter status: (query)  (optional)
     - parameter shopId: (query)  (optional)
     - parameter categoryId: (query)  (optional)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ProductRead]
     */
    open class func listProductsAdminApiV1AdminProductsGet(status: ProductStatus? = nil, shopId: Int? = nil, categoryId: Int? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ProductRead] {
        return try await listProductsAdminApiV1AdminProductsGetWithRequestBuilder(status: status, shopId: shopId, categoryId: categoryId, skip: skip, limit: limit, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Products Admin
     - GET /api/v1/admin/products
     - parameter status: (query)  (optional)
     - parameter shopId: (query)  (optional)
     - parameter categoryId: (query)  (optional)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ProductRead]> 
     */
    open class func listProductsAdminApiV1AdminProductsGetWithRequestBuilder(status: ProductStatus? = nil, shopId: Int? = nil, categoryId: Int? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[ProductRead]> {
        let localVariablePath = "/api/v1/admin/products"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "shop_id": (wrappedValue: shopId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "category_id": (wrappedValue: categoryId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "skip": (wrappedValue: skip?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProductRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Products Seller
     
     - parameter shopId: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ProductRead]
     */
    open class func listProductsSellerApiV1SellerProductsGet(shopId: Int? = nil, status: ProductStatus? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ProductRead] {
        return try await listProductsSellerApiV1SellerProductsGetWithRequestBuilder(shopId: shopId, status: status, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Products Seller
     - GET /api/v1/seller/products
     - parameter shopId: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ProductRead]> 
     */
    open class func listProductsSellerApiV1SellerProductsGetWithRequestBuilder(shopId: Int? = nil, status: ProductStatus? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[ProductRead]> {
        let localVariablePath = "/api/v1/seller/products"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "shop_id": (wrappedValue: shopId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProductRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Shop Products Public
     
     - parameter shopId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ProductRead]
     */
    open class func listShopProductsPublicApiV1ShopsShopIdProductsGet(shopId: Int, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ProductRead] {
        return try await listShopProductsPublicApiV1ShopsShopIdProductsGetWithRequestBuilder(shopId: shopId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Shop Products Public
     - GET /api/v1/shops/{shop_id}/products
     - parameter shopId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ProductRead]> 
     */
    open class func listShopProductsPublicApiV1ShopsShopIdProductsGetWithRequestBuilder(shopId: Int, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[ProductRead]> {
        var localVariablePath = "/api/v1/shops/{shop_id}/products"
        let shopIdPreEscape = "\(APIHelper.mapValueToPathItem(shopId))"
        let shopIdPostEscape = shopIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{shop_id}", with: shopIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProductRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Reject Brand
     
     - parameter brandId: (path)  
     - parameter brandRejectRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BrandRead
     */
    open class func rejectBrandApiV1AdminBrandsBrandIdRejectPatch(brandId: Int, brandRejectRequest: BrandRejectRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> BrandRead {
        return try await rejectBrandApiV1AdminBrandsBrandIdRejectPatchWithRequestBuilder(brandId: brandId, brandRejectRequest: brandRejectRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reject Brand
     - PATCH /api/v1/admin/brands/{brand_id}/reject
     - parameter brandId: (path)  
     - parameter brandRejectRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BrandRead> 
     */
    open class func rejectBrandApiV1AdminBrandsBrandIdRejectPatchWithRequestBuilder(brandId: Int, brandRejectRequest: BrandRejectRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<BrandRead> {
        var localVariablePath = "/api/v1/admin/brands/{brand_id}/reject"
        let brandIdPreEscape = "\(APIHelper.mapValueToPathItem(brandId))"
        let brandIdPostEscape = brandIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{brand_id}", with: brandIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: brandRejectRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BrandRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Reject Product
     
     - parameter productId: (path)  
     - parameter rejectRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func rejectProductApiV1AdminProductsProductIdRejectPatch(productId: Int, rejectRequest: RejectRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await rejectProductApiV1AdminProductsProductIdRejectPatchWithRequestBuilder(productId: productId, rejectRequest: rejectRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reject Product
     - PATCH /api/v1/admin/products/{product_id}/reject
     - parameter productId: (path)  
     - parameter rejectRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func rejectProductApiV1AdminProductsProductIdRejectPatchWithRequestBuilder(productId: Int, rejectRequest: RejectRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/admin/products/{product_id}/reject"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rejectRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Request Brand
     
     - parameter brandRequestCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BrandRead
     */
    open class func requestBrandApiV1SellerBrandsRequestPost(brandRequestCreate: BrandRequestCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> BrandRead {
        return try await requestBrandApiV1SellerBrandsRequestPostWithRequestBuilder(brandRequestCreate: brandRequestCreate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Request Brand
     - POST /api/v1/seller/brands/request
     - parameter brandRequestCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BrandRead> 
     */
    open class func requestBrandApiV1SellerBrandsRequestPostWithRequestBuilder(brandRequestCreate: BrandRequestCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<BrandRead> {
        let localVariablePath = "/api/v1/seller/brands/request"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: brandRequestCreate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BrandRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Submit Product
     
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func submitProductApiV1SellerProductsProductIdSubmitPost(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await submitProductApiV1SellerProductsProductIdSubmitPostWithRequestBuilder(productId: productId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Submit Product
     - POST /api/v1/seller/products/{product_id}/submit
     - parameter productId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func submitProductApiV1SellerProductsProductIdSubmitPostWithRequestBuilder(productId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/seller/products/{product_id}/submit"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update Moderation Config
     
     - parameter moderationConfigUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ModerationConfigRead
     */
    open class func updateModerationConfigApiV1AdminModerationConfigPut(moderationConfigUpdate: ModerationConfigUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ModerationConfigRead {
        return try await updateModerationConfigApiV1AdminModerationConfigPutWithRequestBuilder(moderationConfigUpdate: moderationConfigUpdate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update Moderation Config
     - PUT /api/v1/admin/moderation-config
     - parameter moderationConfigUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ModerationConfigRead> 
     */
    open class func updateModerationConfigApiV1AdminModerationConfigPutWithRequestBuilder(moderationConfigUpdate: ModerationConfigUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ModerationConfigRead> {
        let localVariablePath = "/api/v1/admin/moderation-config"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: moderationConfigUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ModerationConfigRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update Product
     
     - parameter productId: (path)  
     - parameter productUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductRead
     */
    open class func updateProductApiV1SellerProductsProductIdPatch(productId: Int, productUpdate: ProductUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductRead {
        return try await updateProductApiV1SellerProductsProductIdPatchWithRequestBuilder(productId: productId, productUpdate: productUpdate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update Product
     - PATCH /api/v1/seller/products/{product_id}
     - parameter productId: (path)  
     - parameter productUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductRead> 
     */
    open class func updateProductApiV1SellerProductsProductIdPatchWithRequestBuilder(productId: Int, productUpdate: ProductUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductRead> {
        var localVariablePath = "/api/v1/seller/products/{product_id}"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: productUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update Variant
     
     - parameter variantId: (path)  
     - parameter productVariantUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProductVariantRead
     */
    open class func updateVariantApiV1SellerVariantsVariantIdPatch(variantId: Int, productVariantUpdate: ProductVariantUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ProductVariantRead {
        return try await updateVariantApiV1SellerVariantsVariantIdPatchWithRequestBuilder(variantId: variantId, productVariantUpdate: productVariantUpdate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update Variant
     - PATCH /api/v1/seller/variants/{variant_id}
     - parameter variantId: (path)  
     - parameter productVariantUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProductVariantRead> 
     */
    open class func updateVariantApiV1SellerVariantsVariantIdPatchWithRequestBuilder(variantId: Int, productVariantUpdate: ProductVariantUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<ProductVariantRead> {
        var localVariablePath = "/api/v1/seller/variants/{variant_id}"
        let variantIdPreEscape = "\(APIHelper.mapValueToPathItem(variantId))"
        let variantIdPostEscape = variantIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{variant_id}", with: variantIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: productVariantUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProductVariantRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
