//
// RolesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RolesAPI {

    /**
     Assign Permission To Role
     
     - parameter roleId: (path)  
     - parameter assignPermissionRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RoleRead
     */
    open class func assignPermissionToRoleApiV1RolesRoleIdPermissionsPost(roleId: Int, assignPermissionRequest: AssignPermissionRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> RoleRead {
        return try await assignPermissionToRoleApiV1RolesRoleIdPermissionsPostWithRequestBuilder(roleId: roleId, assignPermissionRequest: assignPermissionRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Assign Permission To Role
     - POST /api/v1/roles/{role_id}/permissions
     - parameter roleId: (path)  
     - parameter assignPermissionRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RoleRead> 
     */
    open class func assignPermissionToRoleApiV1RolesRoleIdPermissionsPostWithRequestBuilder(roleId: Int, assignPermissionRequest: AssignPermissionRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<RoleRead> {
        var localVariablePath = "/api/v1/roles/{role_id}/permissions"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: assignPermissionRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Create Role
     
     - parameter roleCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RoleRead
     */
    open class func createRoleApiV1RolesPost(roleCreate: RoleCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> RoleRead {
        return try await createRoleApiV1RolesPostWithRequestBuilder(roleCreate: roleCreate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create Role
     - POST /api/v1/roles/
     - parameter roleCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RoleRead> 
     */
    open class func createRoleApiV1RolesPostWithRequestBuilder(roleCreate: RoleCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<RoleRead> {
        let localVariablePath = "/api/v1/roles/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: roleCreate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete Role
     
     - parameter roleId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteRoleApiV1RolesRoleIdDelete(roleId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteRoleApiV1RolesRoleIdDeleteWithRequestBuilder(roleId: roleId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete Role
     - DELETE /api/v1/roles/{role_id}
     - parameter roleId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteRoleApiV1RolesRoleIdDeleteWithRequestBuilder(roleId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/roles/{role_id}"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Role
     
     - parameter roleId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RoleRead
     */
    open class func getRoleApiV1RolesRoleIdGet(roleId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> RoleRead {
        return try await getRoleApiV1RolesRoleIdGetWithRequestBuilder(roleId: roleId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Role
     - GET /api/v1/roles/{role_id}
     - parameter roleId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RoleRead> 
     */
    open class func getRoleApiV1RolesRoleIdGetWithRequestBuilder(roleId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<RoleRead> {
        var localVariablePath = "/api/v1/roles/{role_id}"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Permissions
     
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [PermissionRead]
     */
    open class func listPermissionsApiV1PermissionsGet(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [PermissionRead] {
        return try await listPermissionsApiV1PermissionsGetWithRequestBuilder(accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Permissions
     - GET /api/v1/permissions/
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[PermissionRead]> 
     */
    open class func listPermissionsApiV1PermissionsGetWithRequestBuilder(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[PermissionRead]> {
        let localVariablePath = "/api/v1/permissions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PermissionRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Roles
     
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [RoleRead]
     */
    open class func listRolesApiV1RolesGet(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [RoleRead] {
        return try await listRolesApiV1RolesGetWithRequestBuilder(accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Roles
     - GET /api/v1/roles/
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[RoleRead]> 
     */
    open class func listRolesApiV1RolesGetWithRequestBuilder(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[RoleRead]> {
        let localVariablePath = "/api/v1/roles/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RoleRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Remove Permission From Role
     
     - parameter roleId: (path)  
     - parameter permissionId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RoleRead
     */
    open class func removePermissionFromRoleApiV1RolesRoleIdPermissionsPermissionIdDelete(roleId: Int, permissionId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> RoleRead {
        return try await removePermissionFromRoleApiV1RolesRoleIdPermissionsPermissionIdDeleteWithRequestBuilder(roleId: roleId, permissionId: permissionId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove Permission From Role
     - DELETE /api/v1/roles/{role_id}/permissions/{permission_id}
     - parameter roleId: (path)  
     - parameter permissionId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RoleRead> 
     */
    open class func removePermissionFromRoleApiV1RolesRoleIdPermissionsPermissionIdDeleteWithRequestBuilder(roleId: Int, permissionId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<RoleRead> {
        var localVariablePath = "/api/v1/roles/{role_id}/permissions/{permission_id}"
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let permissionIdPreEscape = "\(APIHelper.mapValueToPathItem(permissionId))"
        let permissionIdPostEscape = permissionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{permission_id}", with: permissionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
