//
// SellersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SellersAPI {

    /**
     Add Bank Account
     
     - parameter bankAccountCreateRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BankAccountRead
     */
    open class func addBankAccountApiV1SellerBankAccountsPost(bankAccountCreateRequest: BankAccountCreateRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> BankAccountRead {
        return try await addBankAccountApiV1SellerBankAccountsPostWithRequestBuilder(bankAccountCreateRequest: bankAccountCreateRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add Bank Account
     - POST /api/v1/seller/bank-accounts
     - parameter bankAccountCreateRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BankAccountRead> 
     */
    open class func addBankAccountApiV1SellerBankAccountsPostWithRequestBuilder(bankAccountCreateRequest: BankAccountCreateRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<BankAccountRead> {
        let localVariablePath = "/api/v1/seller/bank-accounts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bankAccountCreateRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BankAccountRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Approve Seller
     
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func approveSellerApiV1AdminSellersSellerIdApprovePatch(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await approveSellerApiV1AdminSellersSellerIdApprovePatchWithRequestBuilder(sellerId: sellerId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Approve Seller
     - PATCH /api/v1/admin/sellers/{seller_id}/approve
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func approveSellerApiV1AdminSellersSellerIdApprovePatchWithRequestBuilder(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/approve"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Ban Seller
     
     - parameter sellerId: (path)  
     - parameter statusReasonRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func banSellerApiV1AdminSellersSellerIdBanPatch(sellerId: Int, statusReasonRequest: StatusReasonRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await banSellerApiV1AdminSellersSellerIdBanPatchWithRequestBuilder(sellerId: sellerId, statusReasonRequest: statusReasonRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Ban Seller
     - PATCH /api/v1/admin/sellers/{seller_id}/ban
     - parameter sellerId: (path)  
     - parameter statusReasonRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func banSellerApiV1AdminSellersSellerIdBanPatchWithRequestBuilder(sellerId: Int, statusReasonRequest: StatusReasonRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/ban"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: statusReasonRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Seller Admin
     
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerAdminRead
     */
    open class func getSellerAdminApiV1AdminSellersSellerIdGet(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerAdminRead {
        return try await getSellerAdminApiV1AdminSellersSellerIdGetWithRequestBuilder(sellerId: sellerId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Seller Admin
     - GET /api/v1/admin/sellers/{seller_id}
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerAdminRead> 
     */
    open class func getSellerAdminApiV1AdminSellersSellerIdGetWithRequestBuilder(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerAdminRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerAdminRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get Seller Me
     
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func getSellerMeApiV1SellerMeGet(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await getSellerMeApiV1SellerMeGetWithRequestBuilder(accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Seller Me
     - GET /api/v1/seller/me
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func getSellerMeApiV1SellerMeGetWithRequestBuilder(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        let localVariablePath = "/api/v1/seller/me"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List My Bank Accounts
     
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [BankAccountRead]
     */
    open class func listMyBankAccountsApiV1SellerBankAccountsGet(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [BankAccountRead] {
        return try await listMyBankAccountsApiV1SellerBankAccountsGetWithRequestBuilder(accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List My Bank Accounts
     - GET /api/v1/seller/bank-accounts
     - My accounts plus those of my shops with their own legal entity. Account numbers are never returned.
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[BankAccountRead]> 
     */
    open class func listMyBankAccountsApiV1SellerBankAccountsGetWithRequestBuilder(accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[BankAccountRead]> {
        let localVariablePath = "/api/v1/seller/bank-accounts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[BankAccountRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List My Documents
     
     - parameter shopId: (query) Only this shop&#39;s own documents (optional)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [DocumentRead]
     */
    open class func listMyDocumentsApiV1SellerDocumentsGet(shopId: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [DocumentRead] {
        return try await listMyDocumentsApiV1SellerDocumentsGetWithRequestBuilder(shopId: shopId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List My Documents
     - GET /api/v1/seller/documents
     - My documents, newest first, with review status and rejection reason.
     - parameter shopId: (query) Only this shop&#39;s own documents (optional)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[DocumentRead]> 
     */
    open class func listMyDocumentsApiV1SellerDocumentsGetWithRequestBuilder(shopId: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[DocumentRead]> {
        let localVariablePath = "/api/v1/seller/documents"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "shop_id": (wrappedValue: shopId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[DocumentRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Seller Documents
     
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [DocumentRead]
     */
    open class func listSellerDocumentsApiV1AdminSellersSellerIdDocumentsGet(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [DocumentRead] {
        return try await listSellerDocumentsApiV1AdminSellersSellerIdDocumentsGetWithRequestBuilder(sellerId: sellerId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Seller Documents
     - GET /api/v1/admin/sellers/{seller_id}/documents
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[DocumentRead]> 
     */
    open class func listSellerDocumentsApiV1AdminSellersSellerIdDocumentsGetWithRequestBuilder(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[DocumentRead]> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/documents"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[DocumentRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Sellers
     
     - parameter status: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [SellerRead]
     */
    open class func listSellersApiV1AdminSellersGet(status: String? = nil, search: String? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [SellerRead] {
        return try await listSellersApiV1AdminSellersGetWithRequestBuilder(status: status, search: search, skip: skip, limit: limit, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Sellers
     - GET /api/v1/admin/sellers
     - parameter status: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 50)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[SellerRead]> 
     */
    open class func listSellersApiV1AdminSellersGetWithRequestBuilder(status: String? = nil, search: String? = nil, skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[SellerRead]> {
        let localVariablePath = "/api/v1/admin/sellers"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "search": (wrappedValue: search?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "skip": (wrappedValue: skip?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SellerRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Register Seller
     
     - parameter sellerRegisterRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func registerSellerApiV1SellerRegisterPost(sellerRegisterRequest: SellerRegisterRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await registerSellerApiV1SellerRegisterPostWithRequestBuilder(sellerRegisterRequest: sellerRegisterRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Register Seller
     - POST /api/v1/seller/register
     - parameter sellerRegisterRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func registerSellerApiV1SellerRegisterPostWithRequestBuilder(sellerRegisterRequest: SellerRegisterRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        let localVariablePath = "/api/v1/seller/register"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sellerRegisterRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Reinstate Seller
     
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func reinstateSellerApiV1AdminSellersSellerIdReinstatePatch(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await reinstateSellerApiV1AdminSellersSellerIdReinstatePatchWithRequestBuilder(sellerId: sellerId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reinstate Seller
     - PATCH /api/v1/admin/sellers/{seller_id}/reinstate
     - parameter sellerId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func reinstateSellerApiV1AdminSellersSellerIdReinstatePatchWithRequestBuilder(sellerId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/reinstate"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Reject Seller
     
     - parameter sellerId: (path)  
     - parameter statusReasonRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func rejectSellerApiV1AdminSellersSellerIdRejectPatch(sellerId: Int, statusReasonRequest: StatusReasonRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await rejectSellerApiV1AdminSellersSellerIdRejectPatchWithRequestBuilder(sellerId: sellerId, statusReasonRequest: statusReasonRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reject Seller
     - PATCH /api/v1/admin/sellers/{seller_id}/reject
     - parameter sellerId: (path)  
     - parameter statusReasonRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func rejectSellerApiV1AdminSellersSellerIdRejectPatchWithRequestBuilder(sellerId: Int, statusReasonRequest: StatusReasonRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/reject"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: statusReasonRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Review Document
     
     - parameter sellerId: (path)  
     - parameter docId: (path)  
     - parameter documentReviewRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DocumentRead
     */
    open class func reviewDocumentApiV1AdminSellersSellerIdDocumentsDocIdPatch(sellerId: Int, docId: Int, documentReviewRequest: DocumentReviewRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DocumentRead {
        return try await reviewDocumentApiV1AdminSellersSellerIdDocumentsDocIdPatchWithRequestBuilder(sellerId: sellerId, docId: docId, documentReviewRequest: documentReviewRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Review Document
     - PATCH /api/v1/admin/sellers/{seller_id}/documents/{doc_id}
     - parameter sellerId: (path)  
     - parameter docId: (path)  
     - parameter documentReviewRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DocumentRead> 
     */
    open class func reviewDocumentApiV1AdminSellersSellerIdDocumentsDocIdPatchWithRequestBuilder(sellerId: Int, docId: Int, documentReviewRequest: DocumentReviewRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<DocumentRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/documents/{doc_id}"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let docIdPreEscape = "\(APIHelper.mapValueToPathItem(docId))"
        let docIdPostEscape = docIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{doc_id}", with: docIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: documentReviewRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DocumentRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Submit Document
     
     - parameter documentSubmitRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DocumentRead
     */
    open class func submitDocumentApiV1SellerDocumentsPost(documentSubmitRequest: DocumentSubmitRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DocumentRead {
        return try await submitDocumentApiV1SellerDocumentsPostWithRequestBuilder(documentSubmitRequest: documentSubmitRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Submit Document
     - POST /api/v1/seller/documents
     - parameter documentSubmitRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DocumentRead> 
     */
    open class func submitDocumentApiV1SellerDocumentsPostWithRequestBuilder(documentSubmitRequest: DocumentSubmitRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<DocumentRead> {
        let localVariablePath = "/api/v1/seller/documents"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: documentSubmitRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DocumentRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Suspend Seller
     
     - parameter sellerId: (path)  
     - parameter statusReasonRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func suspendSellerApiV1AdminSellersSellerIdSuspendPatch(sellerId: Int, statusReasonRequest: StatusReasonRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await suspendSellerApiV1AdminSellersSellerIdSuspendPatchWithRequestBuilder(sellerId: sellerId, statusReasonRequest: statusReasonRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Suspend Seller
     - PATCH /api/v1/admin/sellers/{seller_id}/suspend
     - parameter sellerId: (path)  
     - parameter statusReasonRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func suspendSellerApiV1AdminSellersSellerIdSuspendPatchWithRequestBuilder(sellerId: Int, statusReasonRequest: StatusReasonRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/suspend"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: statusReasonRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update Seller Me
     
     - parameter sellerUpdateRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func updateSellerMeApiV1SellerMePatch(sellerUpdateRequest: SellerUpdateRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await updateSellerMeApiV1SellerMePatchWithRequestBuilder(sellerUpdateRequest: sellerUpdateRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update Seller Me
     - PATCH /api/v1/seller/me
     - Send only what changes. Today that is `interest_category_ids`.
     - parameter sellerUpdateRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func updateSellerMeApiV1SellerMePatchWithRequestBuilder(sellerUpdateRequest: SellerUpdateRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        let localVariablePath = "/api/v1/seller/me"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sellerUpdateRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update Shop Limit
     
     - parameter sellerId: (path)  
     - parameter updateShopLimitRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SellerRead
     */
    open class func updateShopLimitApiV1AdminSellersSellerIdShopLimitPatch(sellerId: Int, updateShopLimitRequest: UpdateShopLimitRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SellerRead {
        return try await updateShopLimitApiV1AdminSellersSellerIdShopLimitPatchWithRequestBuilder(sellerId: sellerId, updateShopLimitRequest: updateShopLimitRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update Shop Limit
     - PATCH /api/v1/admin/sellers/{seller_id}/shop-limit
     - parameter sellerId: (path)  
     - parameter updateShopLimitRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SellerRead> 
     */
    open class func updateShopLimitApiV1AdminSellersSellerIdShopLimitPatchWithRequestBuilder(sellerId: Int, updateShopLimitRequest: UpdateShopLimitRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<SellerRead> {
        var localVariablePath = "/api/v1/admin/sellers/{seller_id}/shop-limit"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateShopLimitRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SellerRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
