//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class UsersAPI {

    /**
     Admin Create User
     
     - parameter userAdminCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserRead
     */
    open class func adminCreateUserApiV1UsersPost(userAdminCreate: UserAdminCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UserRead {
        return try await adminCreateUserApiV1UsersPostWithRequestBuilder(userAdminCreate: userAdminCreate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Admin Create User
     - POST /api/v1/users/
     - parameter userAdminCreate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserRead> 
     */
    open class func adminCreateUserApiV1UsersPostWithRequestBuilder(userAdminCreate: UserAdminCreate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<UserRead> {
        let localVariablePath = "/api/v1/users/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userAdminCreate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Assign Role To User
     
     - parameter userId: (path)  
     - parameter assignRoleRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [RoleRead]
     */
    open class func assignRoleToUserApiV1UsersUserIdRolesPost(userId: Int, assignRoleRequest: AssignRoleRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [RoleRead] {
        return try await assignRoleToUserApiV1UsersUserIdRolesPostWithRequestBuilder(userId: userId, assignRoleRequest: assignRoleRequest, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Assign Role To User
     - POST /api/v1/users/{user_id}/roles
     - parameter userId: (path)  
     - parameter assignRoleRequest: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[RoleRead]> 
     */
    open class func assignRoleToUserApiV1UsersUserIdRolesPostWithRequestBuilder(userId: Int, assignRoleRequest: AssignRoleRequest, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[RoleRead]> {
        var localVariablePath = "/api/v1/users/{user_id}/roles"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: assignRoleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RoleRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Deactivate User
     
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserRead
     */
    open class func deactivateUserApiV1UsersUserIdDeactivatePost(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UserRead {
        return try await deactivateUserApiV1UsersUserIdDeactivatePostWithRequestBuilder(userId: userId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Deactivate User
     - POST /api/v1/users/{user_id}/deactivate
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserRead> 
     */
    open class func deactivateUserApiV1UsersUserIdDeactivatePostWithRequestBuilder(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<UserRead> {
        var localVariablePath = "/api/v1/users/{user_id}/deactivate"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get User
     
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserRead
     */
    open class func getUserApiV1UsersUserIdGet(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UserRead {
        return try await getUserApiV1UsersUserIdGetWithRequestBuilder(userId: userId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get User
     - GET /api/v1/users/{user_id}
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserRead> 
     */
    open class func getUserApiV1UsersUserIdGetWithRequestBuilder(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<UserRead> {
        var localVariablePath = "/api/v1/users/{user_id}"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get User Roles
     
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [RoleRead]
     */
    open class func getUserRolesApiV1UsersUserIdRolesGet(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [RoleRead] {
        return try await getUserRolesApiV1UsersUserIdRolesGetWithRequestBuilder(userId: userId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get User Roles
     - GET /api/v1/users/{user_id}/roles
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[RoleRead]> 
     */
    open class func getUserRolesApiV1UsersUserIdRolesGetWithRequestBuilder(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[RoleRead]> {
        var localVariablePath = "/api/v1/users/{user_id}/roles"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RoleRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List Users
     
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [UserRead]
     */
    open class func listUsersApiV1UsersGet(skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [UserRead] {
        return try await listUsersApiV1UsersGetWithRequestBuilder(skip: skip, limit: limit, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Users
     - GET /api/v1/users/
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[UserRead]> 
     */
    open class func listUsersApiV1UsersGetWithRequestBuilder(skip: Int? = nil, limit: Int? = nil, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[UserRead]> {
        let localVariablePath = "/api/v1/users/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "skip": (wrappedValue: skip?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UserRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Reactivate User
     
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserRead
     */
    open class func reactivateUserApiV1UsersUserIdReactivatePost(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UserRead {
        return try await reactivateUserApiV1UsersUserIdReactivatePostWithRequestBuilder(userId: userId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reactivate User
     - POST /api/v1/users/{user_id}/reactivate
     - parameter userId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserRead> 
     */
    open class func reactivateUserApiV1UsersUserIdReactivatePostWithRequestBuilder(userId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<UserRead> {
        var localVariablePath = "/api/v1/users/{user_id}/reactivate"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Remove Role From User
     
     - parameter userId: (path)  
     - parameter roleId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [RoleRead]
     */
    open class func removeRoleFromUserApiV1UsersUserIdRolesRoleIdDelete(userId: Int, roleId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [RoleRead] {
        return try await removeRoleFromUserApiV1UsersUserIdRolesRoleIdDeleteWithRequestBuilder(userId: userId, roleId: roleId, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove Role From User
     - DELETE /api/v1/users/{user_id}/roles/{role_id}
     - parameter userId: (path)  
     - parameter roleId: (path)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[RoleRead]> 
     */
    open class func removeRoleFromUserApiV1UsersUserIdRolesRoleIdDeleteWithRequestBuilder(userId: Int, roleId: Int, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<[RoleRead]> {
        var localVariablePath = "/api/v1/users/{user_id}/roles/{role_id}"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role_id}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RoleRead]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Set User Password
     
     - parameter userId: (path)  
     - parameter userPasswordSet: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserRead
     */
    open class func setUserPasswordApiV1UsersUserIdPasswordPost(userId: Int, userPasswordSet: UserPasswordSet, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UserRead {
        return try await setUserPasswordApiV1UsersUserIdPasswordPostWithRequestBuilder(userId: userId, userPasswordSet: userPasswordSet, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Set User Password
     - POST /api/v1/users/{user_id}/password
     - parameter userId: (path)  
     - parameter userPasswordSet: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserRead> 
     */
    open class func setUserPasswordApiV1UsersUserIdPasswordPostWithRequestBuilder(userId: Int, userPasswordSet: UserPasswordSet, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<UserRead> {
        var localVariablePath = "/api/v1/users/{user_id}/password"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userPasswordSet, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update User
     
     - parameter userId: (path)  
     - parameter userUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserRead
     */
    open class func updateUserApiV1UsersUserIdPatch(userId: Int, userUpdate: UserUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UserRead {
        return try await updateUserApiV1UsersUserIdPatchWithRequestBuilder(userId: userId, userUpdate: userUpdate, accessToken: accessToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update User
     - PATCH /api/v1/users/{user_id}
     - parameter userId: (path)  
     - parameter userUpdate: (body)  
     - parameter accessToken: ()  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserRead> 
     */
    open class func updateUserApiV1UsersUserIdPatchWithRequestBuilder(userId: Int, userUpdate: UserUpdate, accessToken: String? = nil, apiConfiguration: EmarketSellerSDKAPIConfiguration = EmarketSellerSDKAPIConfiguration.shared) -> RequestBuilder<UserRead> {
        var localVariablePath = "/api/v1/users/{user_id}"
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserRead>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
