/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.api.ProductsApi
import com.emarketseller.sdk.model.BrandRead
import com.emarketseller.sdk.model.BrandRejectRequest
import com.emarketseller.sdk.model.BrandRequestCreate
import com.emarketseller.sdk.model.BrandStatus
import com.emarketseller.sdk.model.DelistRequest
import com.emarketseller.sdk.model.HTTPValidationError
import com.emarketseller.sdk.model.ModerationConfigRead
import com.emarketseller.sdk.model.ModerationConfigUpdate
import com.emarketseller.sdk.model.ModerationQueueItemRead
import com.emarketseller.sdk.model.ProductCreate
import com.emarketseller.sdk.model.ProductModerationLogRead
import com.emarketseller.sdk.model.ProductRead
import com.emarketseller.sdk.model.ProductStatus
import com.emarketseller.sdk.model.ProductUpdate
import com.emarketseller.sdk.model.ProductVariantCreate
import com.emarketseller.sdk.model.ProductVariantRead
import com.emarketseller.sdk.model.ProductVariantUpdate
import com.emarketseller.sdk.model.RejectRequest

class ProductsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductsApi
        //val apiInstance = ProductsApi()

        // to test approveBrandApiV1AdminBrandsBrandIdApprovePatch
        should("test approveBrandApiV1AdminBrandsBrandIdApprovePatch") {
            // uncomment below to test approveBrandApiV1AdminBrandsBrandIdApprovePatch
            //val brandId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : BrandRead = apiInstance.approveBrandApiV1AdminBrandsBrandIdApprovePatch(brandId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test approveProductApiV1AdminProductsProductIdApprovePatch
        should("test approveProductApiV1AdminProductsProductIdApprovePatch") {
            // uncomment below to test approveProductApiV1AdminProductsProductIdApprovePatch
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.approveProductApiV1AdminProductsProductIdApprovePatch(productId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test archiveProductApiV1SellerProductsProductIdArchivePost
        should("test archiveProductApiV1SellerProductsProductIdArchivePost") {
            // uncomment below to test archiveProductApiV1SellerProductsProductIdArchivePost
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.archiveProductApiV1SellerProductsProductIdArchivePost(productId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test createProductApiV1SellerShopsShopIdProductsPost
        should("test createProductApiV1SellerShopsShopIdProductsPost") {
            // uncomment below to test createProductApiV1SellerShopsShopIdProductsPost
            //val shopId : kotlin.Int = 56 // kotlin.Int | 
            //val productCreate : ProductCreate =  // ProductCreate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.createProductApiV1SellerShopsShopIdProductsPost(shopId, productCreate, accessToken)
            //result shouldBe ("TODO")
        }

        // to test createVariantApiV1SellerProductsProductIdVariantsPost
        should("test createVariantApiV1SellerProductsProductIdVariantsPost") {
            // uncomment below to test createVariantApiV1SellerProductsProductIdVariantsPost
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val productVariantCreate : ProductVariantCreate =  // ProductVariantCreate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductVariantRead = apiInstance.createVariantApiV1SellerProductsProductIdVariantsPost(productId, productVariantCreate, accessToken)
            //result shouldBe ("TODO")
        }

        // to test deleteVariantApiV1SellerVariantsVariantIdDelete
        should("test deleteVariantApiV1SellerVariantsVariantIdDelete") {
            // uncomment below to test deleteVariantApiV1SellerVariantsVariantIdDelete
            //val variantId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //apiInstance.deleteVariantApiV1SellerVariantsVariantIdDelete(variantId, accessToken)
        }

        // to test delistProductAdminApiV1AdminProductsProductIdDelistPatch
        should("test delistProductAdminApiV1AdminProductsProductIdDelistPatch") {
            // uncomment below to test delistProductAdminApiV1AdminProductsProductIdDelistPatch
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val delistRequest : DelistRequest =  // DelistRequest | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.delistProductAdminApiV1AdminProductsProductIdDelistPatch(productId, delistRequest, accessToken)
            //result shouldBe ("TODO")
        }

        // to test delistProductSellerApiV1SellerProductsProductIdDelistPost
        should("test delistProductSellerApiV1SellerProductsProductIdDelistPost") {
            // uncomment below to test delistProductSellerApiV1SellerProductsProductIdDelistPost
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val delistRequest : DelistRequest =  // DelistRequest | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.delistProductSellerApiV1SellerProductsProductIdDelistPost(productId, delistRequest, accessToken)
            //result shouldBe ("TODO")
        }

        // to test getModerationConfigApiV1AdminModerationConfigGet
        should("test getModerationConfigApiV1AdminModerationConfigGet") {
            // uncomment below to test getModerationConfigApiV1AdminModerationConfigGet
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ModerationConfigRead = apiInstance.getModerationConfigApiV1AdminModerationConfigGet(accessToken)
            //result shouldBe ("TODO")
        }

        // to test getModerationLogApiV1AdminProductsProductIdModerationLogGet
        should("test getModerationLogApiV1AdminProductsProductIdModerationLogGet") {
            // uncomment below to test getModerationLogApiV1AdminProductsProductIdModerationLogGet
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<ProductModerationLogRead> = apiInstance.getModerationLogApiV1AdminProductsProductIdModerationLogGet(productId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test getModerationQueueApiV1AdminModerationQueueGet
        should("test getModerationQueueApiV1AdminModerationQueueGet") {
            // uncomment below to test getModerationQueueApiV1AdminModerationQueueGet
            //val categoryId : kotlin.Int = 56 // kotlin.Int | 
            //val shopId : kotlin.Int = 56 // kotlin.Int | 
            //val onlyFlagged : kotlin.Boolean = true // kotlin.Boolean | 
            //val skip : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<ModerationQueueItemRead> = apiInstance.getModerationQueueApiV1AdminModerationQueueGet(categoryId, shopId, onlyFlagged, skip, limit, accessToken)
            //result shouldBe ("TODO")
        }

        // to test getProductAdminApiV1AdminProductsProductIdGet
        should("test getProductAdminApiV1AdminProductsProductIdGet") {
            // uncomment below to test getProductAdminApiV1AdminProductsProductIdGet
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.getProductAdminApiV1AdminProductsProductIdGet(productId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test getProductPublicApiV1ProductsProductIdGet
        should("test getProductPublicApiV1ProductsProductIdGet") {
            // uncomment below to test getProductPublicApiV1ProductsProductIdGet
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val result : ProductRead = apiInstance.getProductPublicApiV1ProductsProductIdGet(productId)
            //result shouldBe ("TODO")
        }

        // to test getProductSellerApiV1SellerProductsProductIdGet
        should("test getProductSellerApiV1SellerProductsProductIdGet") {
            // uncomment below to test getProductSellerApiV1SellerProductsProductIdGet
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.getProductSellerApiV1SellerProductsProductIdGet(productId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test listBrandsAdminApiV1AdminBrandsGet
        should("test listBrandsAdminApiV1AdminBrandsGet") {
            // uncomment below to test listBrandsAdminApiV1AdminBrandsGet
            //val status : BrandStatus =  // BrandStatus | 
            //val skip : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<BrandRead> = apiInstance.listBrandsAdminApiV1AdminBrandsGet(status, skip, limit, accessToken)
            //result shouldBe ("TODO")
        }

        // to test listBrandsSellerApiV1SellerBrandsGet
        should("test listBrandsSellerApiV1SellerBrandsGet") {
            // uncomment below to test listBrandsSellerApiV1SellerBrandsGet
            //val result : kotlin.collections.List<BrandRead> = apiInstance.listBrandsSellerApiV1SellerBrandsGet()
            //result shouldBe ("TODO")
        }

        // to test listProductsAdminApiV1AdminProductsGet
        should("test listProductsAdminApiV1AdminProductsGet") {
            // uncomment below to test listProductsAdminApiV1AdminProductsGet
            //val status : ProductStatus =  // ProductStatus | 
            //val shopId : kotlin.Int = 56 // kotlin.Int | 
            //val categoryId : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | Case-insensitive partial match on title or SKU (incl. variant SKUs)
            //val skip : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<ProductRead> = apiInstance.listProductsAdminApiV1AdminProductsGet(status, shopId, categoryId, search, skip, limit, accessToken)
            //result shouldBe ("TODO")
        }

        // to test listProductsSellerApiV1SellerProductsGet
        should("test listProductsSellerApiV1SellerProductsGet") {
            // uncomment below to test listProductsSellerApiV1SellerProductsGet
            //val shopId : kotlin.Int = 56 // kotlin.Int | 
            //val status : ProductStatus =  // ProductStatus | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<ProductRead> = apiInstance.listProductsSellerApiV1SellerProductsGet(shopId, status, accessToken)
            //result shouldBe ("TODO")
        }

        // to test listShopProductsPublicApiV1ShopsShopIdProductsGet
        should("test listShopProductsPublicApiV1ShopsShopIdProductsGet") {
            // uncomment below to test listShopProductsPublicApiV1ShopsShopIdProductsGet
            //val shopId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.collections.List<ProductRead> = apiInstance.listShopProductsPublicApiV1ShopsShopIdProductsGet(shopId)
            //result shouldBe ("TODO")
        }

        // to test rejectBrandApiV1AdminBrandsBrandIdRejectPatch
        should("test rejectBrandApiV1AdminBrandsBrandIdRejectPatch") {
            // uncomment below to test rejectBrandApiV1AdminBrandsBrandIdRejectPatch
            //val brandId : kotlin.Int = 56 // kotlin.Int | 
            //val brandRejectRequest : BrandRejectRequest =  // BrandRejectRequest | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : BrandRead = apiInstance.rejectBrandApiV1AdminBrandsBrandIdRejectPatch(brandId, brandRejectRequest, accessToken)
            //result shouldBe ("TODO")
        }

        // to test rejectProductApiV1AdminProductsProductIdRejectPatch
        should("test rejectProductApiV1AdminProductsProductIdRejectPatch") {
            // uncomment below to test rejectProductApiV1AdminProductsProductIdRejectPatch
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val rejectRequest : RejectRequest =  // RejectRequest | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.rejectProductApiV1AdminProductsProductIdRejectPatch(productId, rejectRequest, accessToken)
            //result shouldBe ("TODO")
        }

        // to test requestBrandApiV1SellerBrandsRequestPost
        should("test requestBrandApiV1SellerBrandsRequestPost") {
            // uncomment below to test requestBrandApiV1SellerBrandsRequestPost
            //val brandRequestCreate : BrandRequestCreate =  // BrandRequestCreate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : BrandRead = apiInstance.requestBrandApiV1SellerBrandsRequestPost(brandRequestCreate, accessToken)
            //result shouldBe ("TODO")
        }

        // to test submitProductApiV1SellerProductsProductIdSubmitPost
        should("test submitProductApiV1SellerProductsProductIdSubmitPost") {
            // uncomment below to test submitProductApiV1SellerProductsProductIdSubmitPost
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.submitProductApiV1SellerProductsProductIdSubmitPost(productId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test updateModerationConfigApiV1AdminModerationConfigPut
        should("test updateModerationConfigApiV1AdminModerationConfigPut") {
            // uncomment below to test updateModerationConfigApiV1AdminModerationConfigPut
            //val moderationConfigUpdate : ModerationConfigUpdate =  // ModerationConfigUpdate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ModerationConfigRead = apiInstance.updateModerationConfigApiV1AdminModerationConfigPut(moderationConfigUpdate, accessToken)
            //result shouldBe ("TODO")
        }

        // to test updateProductApiV1SellerProductsProductIdPatch
        should("test updateProductApiV1SellerProductsProductIdPatch") {
            // uncomment below to test updateProductApiV1SellerProductsProductIdPatch
            //val productId : kotlin.Int = 56 // kotlin.Int | 
            //val productUpdate : ProductUpdate =  // ProductUpdate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductRead = apiInstance.updateProductApiV1SellerProductsProductIdPatch(productId, productUpdate, accessToken)
            //result shouldBe ("TODO")
        }

        // to test updateVariantApiV1SellerVariantsVariantIdPatch
        should("test updateVariantApiV1SellerVariantsVariantIdPatch") {
            // uncomment below to test updateVariantApiV1SellerVariantsVariantIdPatch
            //val variantId : kotlin.Int = 56 // kotlin.Int | 
            //val productVariantUpdate : ProductVariantUpdate =  // ProductVariantUpdate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : ProductVariantRead = apiInstance.updateVariantApiV1SellerVariantsVariantIdPatch(variantId, productVariantUpdate, accessToken)
            //result shouldBe ("TODO")
        }

    }
}
