/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.emarketseller.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.emarketseller.sdk.api.UsersApi
import com.emarketseller.sdk.model.AssignRoleRequest
import com.emarketseller.sdk.model.HTTPValidationError
import com.emarketseller.sdk.model.RoleRead
import com.emarketseller.sdk.model.UserAdminCreate
import com.emarketseller.sdk.model.UserPasswordSet
import com.emarketseller.sdk.model.UserRead
import com.emarketseller.sdk.model.UserUpdate

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test adminCreateUserApiV1UsersPost
        should("test adminCreateUserApiV1UsersPost") {
            // uncomment below to test adminCreateUserApiV1UsersPost
            //val userAdminCreate : UserAdminCreate =  // UserAdminCreate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : UserRead = apiInstance.adminCreateUserApiV1UsersPost(userAdminCreate, accessToken)
            //result shouldBe ("TODO")
        }

        // to test assignRoleToUserApiV1UsersUserIdRolesPost
        should("test assignRoleToUserApiV1UsersUserIdRolesPost") {
            // uncomment below to test assignRoleToUserApiV1UsersUserIdRolesPost
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val assignRoleRequest : AssignRoleRequest =  // AssignRoleRequest | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<RoleRead> = apiInstance.assignRoleToUserApiV1UsersUserIdRolesPost(userId, assignRoleRequest, accessToken)
            //result shouldBe ("TODO")
        }

        // to test deactivateUserApiV1UsersUserIdDeactivatePost
        should("test deactivateUserApiV1UsersUserIdDeactivatePost") {
            // uncomment below to test deactivateUserApiV1UsersUserIdDeactivatePost
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : UserRead = apiInstance.deactivateUserApiV1UsersUserIdDeactivatePost(userId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test getUserApiV1UsersUserIdGet
        should("test getUserApiV1UsersUserIdGet") {
            // uncomment below to test getUserApiV1UsersUserIdGet
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : UserRead = apiInstance.getUserApiV1UsersUserIdGet(userId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test getUserRolesApiV1UsersUserIdRolesGet
        should("test getUserRolesApiV1UsersUserIdRolesGet") {
            // uncomment below to test getUserRolesApiV1UsersUserIdRolesGet
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<RoleRead> = apiInstance.getUserRolesApiV1UsersUserIdRolesGet(userId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test listUsersApiV1UsersGet
        should("test listUsersApiV1UsersGet") {
            // uncomment below to test listUsersApiV1UsersGet
            //val skip : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<UserRead> = apiInstance.listUsersApiV1UsersGet(skip, limit, accessToken)
            //result shouldBe ("TODO")
        }

        // to test reactivateUserApiV1UsersUserIdReactivatePost
        should("test reactivateUserApiV1UsersUserIdReactivatePost") {
            // uncomment below to test reactivateUserApiV1UsersUserIdReactivatePost
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : UserRead = apiInstance.reactivateUserApiV1UsersUserIdReactivatePost(userId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test removeRoleFromUserApiV1UsersUserIdRolesRoleIdDelete
        should("test removeRoleFromUserApiV1UsersUserIdRolesRoleIdDelete") {
            // uncomment below to test removeRoleFromUserApiV1UsersUserIdRolesRoleIdDelete
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val roleId : kotlin.Int = 56 // kotlin.Int | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : kotlin.collections.List<RoleRead> = apiInstance.removeRoleFromUserApiV1UsersUserIdRolesRoleIdDelete(userId, roleId, accessToken)
            //result shouldBe ("TODO")
        }

        // to test setUserPasswordApiV1UsersUserIdPasswordPost
        should("test setUserPasswordApiV1UsersUserIdPasswordPost") {
            // uncomment below to test setUserPasswordApiV1UsersUserIdPasswordPost
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val userPasswordSet : UserPasswordSet =  // UserPasswordSet | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : UserRead = apiInstance.setUserPasswordApiV1UsersUserIdPasswordPost(userId, userPasswordSet, accessToken)
            //result shouldBe ("TODO")
        }

        // to test updateUserApiV1UsersUserIdPatch
        should("test updateUserApiV1UsersUserIdPatch") {
            // uncomment below to test updateUserApiV1UsersUserIdPatch
            //val userId : kotlin.Int = 56 // kotlin.Int | 
            //val userUpdate : UserUpdate =  // UserUpdate | 
            //val accessToken : kotlin.String = accessToken_example // kotlin.String | 
            //val result : UserRead = apiInstance.updateUserApiV1UsersUserIdPatch(userId, userUpdate, accessToken)
            //result shouldBe ("TODO")
        }

    }
}
